### ISSUE TITLE
New achievement categories 

### ISSUE THREAD

**Issue by glls** [kevinclement/SimpleArmory#134]
Move supercats :

- Class Hall
- Draenor Garrison
- Scenarios

to a new supercat "Expansion Features"
with subcats:

- Global
- Wintergrasp
- Tol Barad
- Pandaria Scenarios
- Proving Grounds
- Draenor Garrison
- Legion Class Hall
- Island Expeditions
- War Effort

maybe it will be easier if all achievements are imported from WOW-API [under DATA RESOURCES /wow/data/character/achievements](https://dev.battle.net/io-docs) and converted to simplearmory's `data/achievements.json`

**Comment by seirl** [comment]
@kevinclement I've already started working on this, FYI.
