### ISSUE TITLE
Missing companions

### ISSUE THREAD

**Issue by kevinclement** [kevinclement/SimpleArmory#141]
User report
----------
One thing I have noticed though is that the pets from the Island Expeditions are not on the Companions page. Is this just an oversight or is it intentional? I would love to be able to see what I have like the Raiding with Leashes achievements.

**Comment by seirl** [comment]
I generated the list of missing pets:

Pet 143503 missing: Aldrusian Sproutling https://www.wowhead.com/npc=143503
Pet 143796 missing: Barnaby https://www.wowhead.com/npc=143796
Pet 143816 missing: Bloodstone Tunneler https://www.wowhead.com/npc=143816
Pet 143730 missing: Bumbles https://www.wowhead.com/npc=143730
Pet 143795 missing: Captain Nibs https://www.wowhead.com/npc=143795
Pet 143821 missing: Coldlight Surfrunner https://www.wowhead.com/npc=143821
Pet 143803 missing: Craghoof Kid https://www.wowhead.com/npc=143803
Pet 131644 missing: Dart https://www.wowhead.com/npc=131644
Pet 143807 missing: Deathsting Scorpid https://www.wowhead.com/npc=143807
Pet 143464 missing: Dreadtick Leecher https://www.wowhead.com/npc=143464
Pet 143804 missing: False Knucklebump https://www.wowhead.com/npc=143804
Pet 143564 missing: Foulfeather https://www.wowhead.com/npc=143564
Pet 143627 missing: Fozling https://www.wowhead.com/npc=143627
Pet 134406 missing: Francois https://www.wowhead.com/npc=134406
Pet 143499 missing: Fuzzy Creepling https://www.wowhead.com/npc=143499
Pet 143809 missing: Giggling Flame https://www.wowhead.com/npc=143809
Pet 143799 missing: Inky https://www.wowhead.com/npc=143799
Pet 143819 missing: Juvenile Brineshell https://www.wowhead.com/npc=143819
Pet 143802 missing: Kindleweb Spiderling https://www.wowhead.com/npc=143802
Pet 143820 missing: Kunchong Hatchling https://www.wowhead.com/npc=143820
Pet 143810 missing: Laughing Stonekin https://www.wowhead.com/npc=143810
Pet 143738 missing: Lil' Siege Tower https://www.wowhead.com/npc=143738
Pet 143739 missing: Lil' War Machine https://www.wowhead.com/npc=143739
Pet 143813 missing: Littlehoof https://www.wowhead.com/npc=143813
Pet 143812 missing: Mischievous Zephyr https://www.wowhead.com/npc=143812
Pet 143818 missing: Muskflank Calfling https://www.wowhead.com/npc=143818
Pet 143798 missing: Octopode Fry https://www.wowhead.com/npc=143798
Pet 143811 missing: Playful Frostkin https://www.wowhead.com/npc=143811
Pet 143797 missing: Poro https://www.wowhead.com/npc=143797
Pet 143563 missing: Ragepeep https://www.wowhead.com/npc=143563
Pet 143806 missing: Sandshell Chitterer https://www.wowhead.com/npc=143806
Pet 143533 missing: Scabby https://www.wowhead.com/npc=143533
Pet 143794 missing: Scuttle https://www.wowhead.com/npc=143794
Pet 143814 missing: Snapper https://www.wowhead.com/npc=143814
Pet 143817 missing: Snort https://www.wowhead.com/npc=143817
Pet 143801 missing: Sparkleshell Sandcrawler https://www.wowhead.com/npc=143801
Pet 143628 missing: Squawkling https://www.wowhead.com/npc=143628
Pet 143815 missing: Sunscale Hatchling https://www.wowhead.com/npc=143815
Pet 143515 missing: Teeny Titan Orb https://www.wowhead.com/npc=143515
Pet 143808 missing: Thistlebrush Bud https://www.wowhead.com/npc=143808
Pet 143805 missing: Tinder Pup https://www.wowhead.com/npc=143805
Pet 143507 missing: Voidwiggler https://www.wowhead.com/npc=143507
Pet 143822 missing: Voru'kar Leecher https://www.wowhead.com/npc=143822

**Comment by seirl** [comment]
Should be good now.

**Comment by seirl** [comment]
No problem, it's pretty quick to find the missing ones now that I added the npc IDs in `pets.json`.
