### ISSUE TITLE
"Glass of Cow Milk" pet can have two different spells

### ISSUE THREAD

**Issue by seirl** [kevinclement/SimpleArmory#154]
Those two different spells are used for the Pygmy Cow pet:

https://www.wowhead.com/spell=170284/pygmy-cow-g4bc
https://www.wowhead.com/spell=170290/pygmy-cow-bsg

I'm not sure which players get the first one and which get the second one, so I'm not sure how to fix it. I wonder what "G4BC" and "BSG" mean.

**Comment by SilentSigns** [comment]
WarcraftPets has a working implementation that tracks Pygmy Cow, maybe they could offer some insight on how they track it.

**Comment by seirl** [comment]
According to https://www.worldofwargraphs.com/global-stats/pets there's 9% of players with the BSG version and 0.2% with the G4BC version. I'll consider this is a rounding error somewhere and the true version is the BSG one.
