### ISSUE TITLE
Realm doesnt work anymore

### ISSUE THREAD

**Issue by Meepi** [kevinclement/SimpleArmory#157]
I am very sad to say that simple armory doesnt work for EU-Blackmoore anymore. Since i use it all the time I'm very sad and hope this gets fixed soon :((

**Comment by seirl** [comment]
Could you explain what the problem is more in detail? When I select Blackmoore-EU and enter a character name like Rezzodenexo, it goes to https://simplearmory.com/#/eu/blackmoore/Rezzodenexo which seems to work.

**Comment by Meepi** [comment]
Yeees it works again. Yesterday it always said could not fetch charactername.

**Comment by seirl** [comment]
Ah, probably a transient issue then, might be on Blizzard's side. Thanks for the report anyway!
