### ISSUE TITLE
missing "Spirit of the Spring"

### ISSUE THREAD

**Issue by Erigan** [kevinclement/SimpleArmory#158]
I already have the "Spirit of the Spring", but it does not appear, the same as "Glass of Warm Milk"

**Comment by seirl** [comment]
Thanks. I think this is due to a bug in the Blizzard API which doesn't return or used to not return the correct spellid for this pet. I was able to find the spellid manually on Wowhead. It should work now, please reopen if it doesn't.

**Comment by aienia** [comment]
Hello, I just got this pet and I can´t see that it is in the pandaria section at all. Is there still a bug?

**Comment by seirl** [comment]
See #387
