### ISSUE TITLE
Stoneclaw pet not showing up in collection

### ISSUE THREAD

**Issue by GFRRULEZ** [kevinclement/SimpleArmory#159]
For some reason simplearmory will not show that I have the Stoneclaw pet...not a huge deal but I'm curious if its a bug of some kind; as I do have it

**Comment by seirl** [comment]
Hi, could you link me your armory or SimpleArmory profile?

**Comment by seirl** [comment]
Did you get it long ago? I just checked and it shows up in my profile.

**Comment by GFRRULEZ** [comment]
Closing issue...made the nub mistake of not clearing my cache...once done the pet showed up....thx all the same!
