### ISSUE TITLE
Pets not showing after 8.2?

### ISSUE THREAD

**Issue by Kaerei** [kevinclement/SimpleArmory#164]
This is what shows anytime I try and search anyone. Are we just waiting for another update?

https://imgur.com/a/bzibS4R

Thanks!

**Comment by seirl** [comment]
I think the armory is broken, I got that a few hours ago too.

**Comment by Kaerei** [comment]
That makes sense. My Xu-Fu collection won't pull either. I didn't even think about that. Thank you!
