### ISSUE TITLE
Migrate to new Profile API

### ISSUE THREAD

**Issue by Avetixz** [kevinclement/SimpleArmory#166]
Since 8.2, the old Community API only shows character-specific achievements as completed. This is fixed in the new [Profile API](https://us.battle.net/forums/en/bnet/topic/20772457051). The Profile API only returns data for characters that have logged on since the release of 8.2, additionally, the Community API seems to still return account-wide achievement data correctly for old characters, so I suppose the Community API should still be used for old characters as a fail-safe.

There are still some things missing from the Profile API, the Character Profile endpoint references a Collections endpoint, which isn't available yet, so that will probably include mounts and pets.

**Comment by seirl** [comment]
Thanks for the info! Would you want to contribute a pull request to implement that?

**Comment by seirl** [comment]
Apparently Blizzard is investigating a way to fix the old APIs: https://us.battle.net/forums/en/bnet/topic/20772587059

**Comment by Avetixz** [comment]
Huh, it seems like the old API was fixed while I was working on an implementation. I guess I'll create a pull request anyway since Blizzard is advocating migrating to the new APIs, but I do think my implementation is a little messy.

**Comment by Avetixz** [comment]
There is a small discrepancy in what achievements are being shown. The old API seems to show faction-wide achievement progress like before, but the new API now shows account-wide progress. So if you get a horde-specific achievement on one character, the old API doesn't show the alliance-equivalent as completed on an alliance character, but the new API does.

**Comment by seirl** [comment]
That actually sounds great, it allows us to implement filters that allow you to show cross-faction achievements too!
