### ISSUE TITLE
Some icons missing

### ISSUE THREAD

**Issue by Wizeowel** [kevinclement/SimpleArmory#170]
Since 8.2 some icons are missing. Looking through the source it seems these have image data instead of a url.

For example achievement 4637 heroic-fall-of-the-lich-king-25-player has 
`<img ng-src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==">`
while it should have something like this (I guess)
`<img ng-src="//wow.zamimg.com/images/wow/icons/medium/achievement_dungeon_icecrown_frostmourne.jpg" src="//wow.zamimg.com/images/wow/icons/medium/achievement_dungeon_icecrown_frostmourne.jpg">`

**Comment by seirl** [comment]
Hi! I had this bug too but it apparently fixed itself, I can no longer reproduce. I think it might have been an external problem?

Anyway, I'll close this for now but if it's not fixed for you don't hesitate to reopen it.

**Comment by Wizeowel** [comment]
It's still an issue. At work and at home. I tried reloading the character, tried on other characters from my account. 

It seems to be confined to the 'meta' achievements. I do have that setting in the interface that says show character achievements only, but both blizz armory and wowhead profile is showing those correctly completed.

**Comment by seirl** [comment]
Have you tried to force refresh? It works fine for my character: https://simplearmory.com/#/eu/archimonde/ana%C3%BFza/achievements/dungeons

Could you link your character, if you think it's character-specific?

**Comment by Wizeowel** [comment]
Okay, figured it out. It's indeed the setting in Social: "Display Only Character Achievements to Others" (Turning this option on will only display your character achievements to when people inspect you or use the Blizzard website or mobile app). 

If I turn that off, the achieves reappear on simplearmory. But this setting doesn't affect Blizz website nor wowhead , only simplearmory. Perhaps something in the (json?) isn't parsing properly when that option is selected?

Try switching it on, on your toon?

**Comment by Wizeowel** [comment]
Tested on 3 toons. Totally reproducible for me. Raid meta achievements disappear when Display Only Character Achievements to Others is selected, even though the constituent achievements are showing as completed.

[https://imgur.com/a/PuXOb3e](url)

**Comment by seirl** [comment]
I didn't understand when you said "icons missing" that you were talking about them being shown at "not obtained". It sounded like you meant the icons were bugged, not that it showed up like you didn't collect them.

Anyway, I don't know how much of this is related to the new Character Profile API, but there's nothing we can do on our side except implementing #166, so I'll let this closed as a duplicate.

**Comment by Wizeowel** [comment]
Yes sorry, at first I thought the icons themselves were not loading, because I certainly had those achievements. It's strange that it's only an issue with the meta achieves.
