### ISSUE TITLE
Bower is obsolete

### ISSUE THREAD

**Issue by Tynael** [kevinclement/SimpleArmory#174]
Hey!

While installing the repo on my local machine, running the command `npm install -g grunt-cli bower` spit the following warning message:

```npm WARN deprecated bower@1.8.8: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
/usr/bin/bower -> /usr/lib/node_modules/bower/bin/bower
/usr/bin/grunt -> /usr/lib/node_modules/grunt-cli/bin/grunt
+ grunt-cli@1.3.2
+ bower@1.8.8
added 151 packages from 122 contributors in 6.782s
```

Do you think it is manageable to move from Bower to either Yarn, Webpack or Parcel as recommended in the above message?

**Comment by seirl** [comment]
The website was rewritten with Svelte, this issue is obsolete.
