### ISSUE TITLE
Knights of the Ebon Blade

### ISSUE THREAD

**Issue by arctic95** [kevinclement/SimpleArmory#184]
Knights of the Ebon Blade dont show in my reputation despite the friendly standing and it showing in normal WoW armory

**Comment by seirl** [comment]
The ID looks good in the database so I feel like this might be a Blizzard API issue. Will investigate further.

**Comment by Tynael** [comment]
I couldn't reproduce this issue.
The Knights of the Ebon Blade rep is being shown in reputation section.

**Comment by seirl** [comment]
Indeed, this looks fixed. Thanks for checking.
