### ISSUE TITLE
Remove the "Legion keymaster" achievement from dungeons/raids, as it is already unobtainable since the bfa prepatch

### ISSUE THREAD

**Issue by Jechtman** [kevinclement/SimpleArmory#186]
it should be removed

**Comment by seirl** [comment]
I think this is more of a Blizzard issue at this point, the achievement is still not a FoS and still gives achievement point. I think it's wiser to let it here until they move it to FoS, to avoid forgetting about it.

I'll tag it as a Blizzard bug.

**Comment by seirl** [comment]
Blizzard moved the achievement in the Legacy category in 9.1, and 5942c98fc320d4d4b5cecb03ebe9780b9e51e928 reflects this change.
