### ISSUE TITLE
15th Anniversary Mount "Ensorcelled Everwyrm" not tracked 

### ISSUE THREAD

**Issue by Zerbersteras** [kevinclement/SimpleArmory#187]
The title says it all, thanks for your effort!

**Comment by seirl** [comment]
Thanks for the report!

Ensorcelled Everwyrm is not a 15th anniversary mount, it's a mount for the Shadowlands collector edition.

This was already fixed by @RavageJ in fa36f354439b3785811542c82f5c4da732d1afea (PR #185 ).
