### ISSUE TITLE
Can't update toys list on my character profile

### ISSUE THREAD

**Issue by nulea** [kevinclement/SimpleArmory#194]
Character : EU/Nulea - https://worldofwarcraft.com/fr-fr/character/eu/elune/nulea

Hello!

I have the addon installed, but when I copy/paste the generated list as usual... Nothing happens.
What am I doing wrong?

When I hit the "Save" button, the navigator (Firefox 71.0) console says :
```
Parsing toys.json...
WARN: Found item "54651" from character but not in db.
WARN: Found item "54653" from character but not in db.
```

I tried removing these ids from the list but it doesn't seem to help...
Any idea?

Thanks!

**Comment by nulea** [comment]
Now same but with additional IDs ;-)

WARN: Found item "172219" from character but not in db.
WARN: Found item "172222" from character but not in db.
WARN: Found item "172223" from character but not in db.

**Comment by seirl** [comment]
Hi! Could you paste your toy string here so that I can debug the issue? Thank you.

**Comment by nulea** [comment]
Hello!

Well... I tried it now, and it... just worked™.
I guess the messages in the navigator console weren't related to the problem, cause I still have them and it managed to update my toys list.

I close the issue for now, will come back if it happens again.
Thank you!
