### ISSUE TITLE
Squeakers, the Trickster (Shop Mount) not tracked correctly

### ISSUE THREAD

**Issue by Zerbersteras** [kevinclement/SimpleArmory#207]
the Mount is showing missing, although it has been obtained

**Comment by seirl** [comment]
Sadly this kind of things is almost always a blizzard bug, especially with store mounts. They never add them to the API in time. Might have to wait until the next API update.

**Comment by kevinclement** [comment]
given I was migrating to newer api I checked this one today and it looks like it's working now.  I have the mount and could confirm on my character.

![image](https://user-images.githubusercontent.com/132959/77129334-e3ace000-6a10-11ea-9b23-e2dce4b62451.png)
