### ISSUE TITLE
Achievement "The Fourth War" not showing up as completed.

### ISSUE THREAD

**Issue by ChapterXXX** [kevinclement/SimpleArmory#213]
Quest - The 4th War (done but missing)

**Comment by seirl** [comment]
Please explain the problem you're encountering, this is completely unintelligible.

**Comment by ChapterXXX** [comment]
So, under Quests, War Campaign, 'The Fourth War' isn't reporting as complete anymore, but was completed ages ago. I've checked a couple of friends who have completed it previously and they are both flagged as none complete.

**Comment by seirl** [comment]
So you're talking about an achievement missing, not a quest? Could you give a link to a profile that has this issue?

**Comment by ChapterXXX** [comment]
Sure:
https://simplearmory.com/#/eu/terokkar/Morloch

Achievements/Quests/War Campaign 'The Fourth War'

**Comment by seirl** [comment]
This is a Blizzard bug, they removed this achievement from their API for some reason.

**Comment by seirl** [comment]
This appears to be fixed in the community API.
