### ISSUE TITLE
Pop-up information is not shown via mouse-over

### ISSUE THREAD

**Issue by Rauko** [kevinclement/SimpleArmory#228]
Mouse-overed "box" is lighted-up but the pop-up information it not shown

http://prntscr.com/riyo4x

**Comment by kevinclement** [comment]
This is handled by wowhead scripts that get loaded in page.  Could it be that maybe you have an extension or something that might be blocking that script from loading?  

I use ublock origin and don't see this problem. I tested with your character and seemed to be okay.

There might be information in the console of the browser that might help too.  If you right click inside the page and select 'Inspect', then switch to the console tab, you might see an error there that could help.

![image](https://user-images.githubusercontent.com/132959/77127432-a8f37980-6a09-11ea-9de9-d0c18522e9b4.png)

**Comment by Rauko** [comment]
it worked ok before last SA maintenance

**Comment by seirl** [comment]
Closing for now, please shout out if it happens again!
