### ISSUE TITLE
Classmounts missing

### ISSUE THREAD

**Issue by Rauko** [kevinclement/SimpleArmory#232]
Legion Classmounts are missing in Legion mountpack, also no information about DHs felsaber

Legion mounts with no classmonts - http://prntscr.com/rmeimy
no felsaber for DH in Others anymore - http://prntscr.com/rmejw9

**Comment by gmsbaptista** [comment]
Also came here to report this bug

**Comment by Zerbersteras** [comment]
Also missing for Hunters

**Comment by Roguinaa** [comment]
Also missing for Rogues

**Comment by seirl** [comment]
Fixed in #232
