### ISSUE TITLE
Diacritics in realm name

### ISSUE THREAD

**Issue by a-lutz** [kevinclement/SimpleArmory#233]
Hello,

Since a few days it's been impossible to load characters on realms with diacritics - Chants Éternels (EU) as for me.
The character choice form leads to https://simplearmory.com/#/eu/chants-eternels/Pandraa then https://simplearmory.com/#/error/chants-eternels/Pandraa

https://simplearmory.com/#/error/chants-éternels/Pandraa is answering correctly, though.

Previously URLs with chants-eternels were responding okay.

**Comment by seirl** [comment]
Fixed by #250
