### ISSUE TITLE
Allied Race Mount Category

### ISSUE THREAD

**Issue by Zerbersteras** [kevinclement/SimpleArmory#236]
Suggestion:
Highmountain/Nightborn & Voidelf/Lightforged should not be in BFA Allied Race but instead in a Legion Allied Race category

**Comment by Roguinaa** [comment]
Legion didn't have Allied Races as a feature, they we're added with BFA. You couldn't make one in Legion if you hadn't prepurchased BFA, so putting them in Legion would not make sense.
