### ISSUE TITLE
Blizzard API returns a 404 error for some characters

### ISSUE THREAD

**Issue by tsakm** [kevinclement/SimpleArmory#237]
Tried all possible solutions and still cant fetch.
example 
Server Ravencrest EU
name Kekron

tried multiple browsers and lowercase letters and always get the same
Cant fetch character error

**Comment by Tynael** [comment]
Same issue as https://github.com/kevinclement/SimpleArmory/issues/245.

**Comment by seirl** [comment]
Doesn't seem to be the same issue, Ravencrest doesn't have accents in its realm name.

**Comment by seirl** [comment]
This seems to be a Blizzard bug that is specific to your character. The API returns a 404 error when trying to fetch your character like here:

https://eu.api.blizzard.com/profile/wow/character/ravencrest/kekron/collections/pets?namespace=profile-eu&locale=en_US&access_token=CHANGEME

This is out of our control. Maybe your best shot is to report this error here: https://us.forums.blizzard.com/en/blizzard/c/api-bug-report/19

**Comment by tsakm** [comment]
Indeed it was Blizzard's fault. Case closed.

**Comment by seirl** [comment]
Cool! By curiosity, how did you manage to get it fixed?
