### ISSUE TITLE
None of my "collectables" will load at all

### ISSUE THREAD

**Issue by radochh** [kevinclement/SimpleArmory#243]
When i click it its just a blank page

**Comment by seirl** [comment]
Please provide more details, like you character and realm name.

**Comment by Tynael** [comment]
@radochh When on that page, please press F12, go to Console tab and take a screenshot.

**Comment by seirl** [comment]
Closing the issue as the reporter didn't provide the requested feedback. Feel free to comment in this issue if your problem persists.
