### ISSUE TITLE
Can't search for my character

### ISSUE THREAD

**Issue by AnaMRosa** [kevinclement/SimpleArmory#245]
Been trying (today is the 3rd day in a row) to search for my character in simplearmory, but I receive this error message: Could not fetch 'atlas' from server 'aggra-portugues'. Click here to try again. I was able to search for my character in the past.
Character: Atlas
Realm: Aggra (Português)

**Comment by Tynael** [comment]
There might be an issue with Blizzard's API because the request gives a 404 error.
`{"code":404,"type":"BLZWEBAPI00000404","detail":"Not Found"}`

**Comment by Furfx** [comment]
Looks like the official armory uses accented char in the URL.
https://worldofwarcraft.com/en-gb/character/eu/aggra-portugu%C3%AAs/atlas

https://armorystats.info/eu/aggra-portugu%C3%AAs/atlas/
Returns the correct data.

However the form on Simple Armory will use the URL without the accented chars. If we had them it works : 
https://simplearmory.com/#/eu/aggra-portugu%C3%AAs/atlas
