### ISSUE TITLE
Multiple visual mistakes/bugs

### ISSUE THREAD

**Issue by Roguinaa** [kevinclement/SimpleArmory#254]
Wrong Icons:
- Fabious (Icon is seahorse)
- Inkscale Deepseeker (icon is seahorse)
- Mechagon Mechanocat (icon is battle pet)
- Both Mechagon spidertanks (I dont even know what icon it is I just know its not the right one)

Other:
- Vashj'r Seahorse missing even on characters that have it

**Comment by seirl** [comment]
> Vashj'r Seahorse missing even on characters that have it

This bullet point is a duplicate of #231, #234, #247 and #248.

**Comment by seirl** [comment]
New data fixer enforces rigorous matching of icons with the game, so this issue should no longer happen.
