### ISSUE TITLE
Vashj'ir Seahorse not tracked correctly

### ISSUE THREAD

**Issue by gibio123** [kevinclement/SimpleArmory#256]
The Cataclysm Quest Mount Vashj'ir Seahorse is not correctly displayed (missing instead of obtained on my profile)
(https:// https://simplearmory.com/#/us/azralon/gibio/collectable/mounts)
Thanks as always for putting in so much effort into this website!

**Comment by seirl** [comment]
Duplicate of #231, #234, #247, #248, #254 and #255.
