### ISSUE TITLE
Mount information not pulling through

### ISSUE THREAD

**Issue by OblixUser** [kevinclement/SimpleArmory#257]
As of yesterday only placeholder for images and no names are pulling though.  

![saissue](https://user-images.githubusercontent.com/66202989/83350039-0e7cb400-a331-11ea-8203-133530afbab5.PNG)

**Comment by seirl** [comment]
I don't have this issue here, maybe it was a transient problem? Do you still see this problem?

**Comment by OblixUser** [comment]
Hi - wasn't expecting a reply so fast.  Sadly yes the issue continues.

**Comment by seirl** [comment]
Could you send a link to your profile?

Can you check the developer console (F12 on chrome) and show us if there are any errors?

**Comment by OblixUser** [comment]
Hi 
https://simplearmory.com/#/eu/kazzak/obel%C3%ADx/collectable/mount

![sa01](https://user-images.githubusercontent.com/66202989/83409290-09d8fe00-a40c-11ea-9240-f6ac0cc4c9d9.PNG)
![sa02](https://user-images.githubusercontent.com/66202989/83409356-28d79000-a40c-11ea-95e0-9f95a00e33c6.PNG)
![sa03](https://user-images.githubusercontent.com/66202989/83409384-368d1580-a40c-11ea-93eb-f578193ea6fb.PNG)
![sa04](https://user-images.githubusercontent.com/66202989/83409406-4278d780-a40c-11ea-90cf-53d9c3478c68.PNG)

**Comment by seirl** [comment]
Weird, have you tried disabling your adblocker?

**Comment by OblixUser** [comment]
It finally started working again - I didnt do anything on my side software or ad block wise

________________________________
