### ISSUE TITLE
Can not fetch my characters - other characters seem to work fine

### ISSUE THREAD

**Issue by vronikas** [kevinclement/SimpleArmory#259]
Thank you for the awsome site!

Whenever I try to look up my characters (any of them) I get:
https://simplearmory.com/#/error/blackhand/Korvus
Error
Could not fetch 'Korvus' from server 'blackhand'. Click here to try again.

This is Blackhand EU, other servers do not work either with my characters.

All of my other characters get the same error (tried other servers, created new characters, etc. nothing works, same error)

I have tried different browsers, computers, ISPs, nothing, same error.

When I lookup other chracters (not mine) it works:
https://simplearmory.com/#/eu/blackhand/vayrala/collectable/mounts

Can you please help me? Thank you!

**Comment by glls** [comment]
https://worldofwarcraft.com/en-gb/character/eu/blackhand/korvus/achievements

the official site doesnt work either, I think you should create a ticket at Blizzard support

**Comment by glls** [comment]
update: after refreshing sometimes it wotks on official site now, maybe it will start working from the API, too
might had some internal error or something at the official server
