### ISSUE TITLE
Add bengal tiger

### ISSUE THREAD

**Issue by Shaux77** [kevinclement/SimpleArmory#265]
Theres a guy (Lunastar-Muradin) with the bengal tiger mount, it would be cool if yall would add it to the site :)

**Comment by Oath166** [comment]
She's a girl and it was rewarded as a Make-A-Wish request for her.. I don't think adding the mount would change anything.

**Comment by seirl** [comment]
Heh, it's a fun easter egg, I implemented it anyway :-)
