### ISSUE TITLE
Planner: Grand Black War Mammoth doesn't show up as obtained.

### ISSUE THREAD

**Issue by Goten87** [kevinclement/SimpleArmory#271]
the planner is showing mounts i already have like the Grand Black War Mammoth i have that one but it still shows up in the planner
is there something wrong with the API or the website ?

**Comment by Harudo** [comment]
I was gonna make a ticket about this but I also have this issue and I have the mount

**Comment by Kehyll** [comment]
Same here. Showing the grand war black Mammoth (with a line that lists alliance races) although I have it. I checked there wasn't a faction specific mount and it does not seem so.

**Comment by PanKoloban** [comment]
This bug is still relevant.

**Comment by DjRicko** [comment]
Still bugged: https://simplearmory.com/#/eu/twisting-nether/gezruk/collectable/mounts
Armory website shows it correctly as being in collection. Also why isn't it listed under Wrath of the Lich King in the overview?

**Comment by bigtigerx** [comment]
I am having this same issue. :(
https://simplearmory.com/#/us/thrall/bigtigerx/collectable/mounts

**Comment by seirl** [comment]
Fixed by #300
