### ISSUE TITLE
Mount Tab Empty

### ISSUE THREAD

**Issue by PhilCherg** [kevinclement/SimpleArmory#273]
The mount tab shows nothing. I tried waiting but even after 10 minutes there was nothing.

**Comment by seirl** [comment]
Please provide a link to your character in SimpleArmory so that we can investigate.
@Imfernus you are welcome to do the same since you reported a similar issue (#274)

**Comment by seirl** [comment]
Closing after no news from reporter. Probably obsolete with the rewrite anyway.
