### ISSUE TITLE
Missing Eternal Traveler's Hearthstone

### ISSUE THREAD

**Issue by thomasthebear** [kevinclement/SimpleArmory#275]
Anytime I'd been checking and updating my toys on the site, I'd always noticed that I was showing one less then my actual total, and could never quite understand what it was missing. Finally decided to look into it, and happened to realize the [Eternal Traveler's Hearthstone](https://www.wowhead.com/item=172179/eternal-travelers-hearthstone), from the Shadowlands Epic Edition, didn't seem to be showing anywhere. Looked and the addon in game is picking up the Item's ID `[172179]` but even when removed from the text string, it doesn't change anything on the page. 

Anyway to possibly add this in?

**Comment by thomasthebear** [comment]
Should specify this is the case on the main website, not a localized version I've cloned. Don't know if that makes a difference or not.

**Comment by seirl** [comment]
Fixed in db79182300c99e471090db7b0f478addc8185710
