### ISSUE TITLE
Glorious Felcrusher Missing

### ISSUE THREAD

**Issue by Demonicka** [kevinclement/SimpleArmory#276]
I got this about 24 hours ago and it's not showing. Please update it, thx.
Character: Demonïcka-Stormrage

**Comment by seirl** [comment]
The mount is there and works well for characters who have it. If there's a bug, it's on the Blizzard side. Maybe try to log off and on again, and check your character privacy settings.

**Comment by Demonicka** [comment]
Done so, and definitely have the mount.
![WoWScrnShot_081120_063523aa](https://user-images.githubusercontent.com/56662691/90003310-bfb09c00-dc48-11ea-8d3c-11c44263318f.jpg)

**Comment by seirl** [comment]
Again, the problem is that the Blizzard API doesn't return that you have the mount. You'll have to figure that problem yourself, this is out of our hands. Maybe just wait longer until they invalidate their cache or something.
