### ISSUE TITLE
Unable to fetch all characters

### ISSUE THREAD

**Issue by calvinpn** [kevinclement/SimpleArmory#281]
Hello,

I am unable to fetch any of my characters on SimpleArmory. There are no special characters in any of the names, no recent services (like name change, server transfer, etc), have had active game time since the beginning of the pandemic (March-ish, and before that for like 10+ years straight), and I log into them all regularly since March. The official WoW Armory lists all of them just fine and they are all updated/current. Of note, Wowhead is unable to find any of my characters either (it says character not found). I tried looking up random characters I see in Orgrimmar and the random few ones I've tried all pull up just fine so it must just be my characters. Not sure how to proceed...

Server is Frostwolf-US (recently merged with a bunch of servers, but one of my guildies pulls up just fine), some of my toons names are Kaoya, Audien, Afterglow.

Appreciate any help or advice :)

**Comment by arkitrin** [comment]
Same issue. Attempted to look up my characters from multiple different servers and I'm getting a whole lot of nothing. Skywall, Windrunner, Frostmane, and Proudmoore. Characters are all well over a year old and the official armory has them correct. Multiple devices tried, different browsers, even had a friend from the other side of the country look me up and they received the same error. Shame-Skywall, Lustrocity-Proudmoore, Shutendoji-Windrunner

**Comment by calvinpn** [comment]
I'll also add that I have a character of the opposing faction on on a different server (Sargeras-US) that I also tried before (just forgot to mention in my original post) and that one will not pull up either so I'm inclined to think that it may be an "account-wide" thing.

Thank you and appreciate any help you're able.

**Comment by calvinpn** [comment]
As an additional effort to see if there was something wrong with my account internally, I sent a in game ticket and they responded that that it is not something they can control regarding tools such as these that are outside of their control and recommended to try to figure it out with the owners of such tools.

Thank you :)

**Comment by madymonk** [comment]
Same problem since ~three weeks. Before everything worked fine for months... Then I didnt play for like a week and “error couldnt fetch data“. Tried a lot, nothing worked out. My friends character is just fine. Server is EU Blackrock, no merging so far. Oh and same problem on magpie wow pets webpage.

**Comment by arkitrin** [comment]
I think I've found out what's wrong. I went into bnet privacy settings and turned "Game Data And Profile Privacy" on. Guessing we all turned it off at some point because privacy concerns but its the API soooo, yeah.

**Comment by calvinpn** [comment]
I will give this a try! Just went in and changed the setting myself. It says my preference is still processing so I'll wait for that to go away, refresh my armory page and give SimpleArmory a try again. Appreciate your investigative efforts and hope it works for me! Will report back.

**Comment by calvinpn** [comment]
@arkitrin This worked for me! Thank you! You figured it out before a dev came to the rescue XD
