### ISSUE TITLE
Already Obtained: Grand Black War Mammoth Showing on Mount Plan

### ISSUE THREAD

**Issue by CharmCityNorth** [kevinclement/SimpleArmory#282]
I obtained the Reins of the Grand Black War Mammoth years ago, and recently noticed it was added to my Mount Plan even though my character already shows it as obtained.

**Comment by Oath166** [comment]
Same issue here for me! And the tracking isn't up to date either.. I'm at 238 in game and on here I'm at 225.

**Comment by seanpeters86** [comment]
Same for me as well

**Comment by cmburche** [comment]
ditto ^^^

**Comment by Lusolock** [comment]
same issue for me

**Comment by jbryson3** [comment]
I just ran into this bug so I added a PR to fix it

**Comment by jbryson3** [comment]
Dupe of https://github.com/kevinclement/SimpleArmory/issues/271

**Comment by seirl** [comment]
Duplicate of #271
