### ISSUE TITLE
Pet Battle and Collections are not showing up!

### ISSUE THREAD

**Issue by Marotinhah** [kevinclement/SimpleArmory#283]
The achievements of pet battle and collections are not appearing in my main character. However, they appear normal in my alts.
I already sent a ticket to Blizzard, and they said they couldn't do anything.

**Comment by Marotinhah** [comment]
Marotinhah@Azralon

**Comment by seirl** [comment]
You probably have this option enabled in-game:

Game Menu | Interface | Social | Display Only Character Achievements To Others

Try to disable it, it should fix the issue.
