### ISSUE TITLE
Missing mount ?

### ISSUE THREAD

**Issue by yimgame** [kevinclement/SimpleArmory#284]
Hey is just beatufull your work.

I dont see Houlon at plan ? i am right ?

https://www.wowhead.com/npc=73167/huolon

Actually drop 

https://www.wowhead.com/item=104269/reins-of-the-thundering-onyx-cloud-serpent

Any way u rock !

![image](https://user-images.githubusercontent.com/544669/95156176-4925ab80-076c-11eb-8f5e-63c6bf9988b5.png)

**Comment by yimgame** [comment]
i have no Houlon mount but is not under plan.

The plan idea is just brillant...

![image](https://user-images.githubusercontent.com/544669/95156302-999d0900-076c-11eb-921f-2dd7c08cb57b.png)

**Comment by seirl** [comment]
It doesn't really make sense to include Huolon as part of the planner, as it can be farmed repeatedly every time it respawns. There is no weekly lockout, so it's weird to include it in a route and makes you lose a lot of time.

Closing. Thanks for the report!
