### ISSUE TITLE
Old RaF Mounts Unobtainable

### ISSUE THREAD

**Issue by Roguinaa** [kevinclement/SimpleArmory#285]
Perhaps hide the old 5 RaF mounts like how it hides unobtained AOTC mounts?

They're no longer obtainable as the old RaF program is no more, so it's just empty space that can never be filled for most.

I'd say hide it and only make a mount appear if you own it. (I only own the Nightwing, so I'd only see the Nightwing and the new RaF mounts) This is already done for Ahead of the Curve mounts, so perhaps the same can be copied for RaF minus the 2 new mounts?

**Comment by seirl** [comment]
Done in 8d2452d
