### ISSUE TITLE
My profile wont show up

### ISSUE THREAD

**Issue by SellAllThisStuff** [kevinclement/SimpleArmory#297]
Error
Could not fetch 'персичек' from server 'goldrinn'. Click here to try again.

Thats happens on all characters. I tried random ppl's accounts from my server and they worked, even inactive at the moment. 

Персичек, Goldrinn EU

**Comment by michaelgthomas** [comment]
This appears to have something to do with Blizzard accepting cyrillic characters on the API - it says that the string has to be set to lowercase, but in this case it does seem to be the case.

Tried fiddling around with this, but even using the playground API I couldn't get it to work, get this issue:

![image](https://user-images.githubusercontent.com/43745389/97696025-a3850400-1aad-11eb-85cd-d45484639260.png)

![image](https://user-images.githubusercontent.com/43745389/97696082-b13a8980-1aad-11eb-9bd4-d7d35e7384bd.png)


Not sure if there is a workaround for this.

**Comment by seirl** [comment]
Looks like Blizzard fixed their stuff, your profile can now be properly accessed: https://simplearmory.com/#/eu/goldrinn/%D0%BF%D0%B5%D1%80%D1%81%D0%B8%D1%87%D0%B5%D0%BA/collectable/mounts
