### ISSUE TITLE
Ulduar Mimiron planner

### ISSUE THREAD

**Issue by Otsoko** [kevinclement/SimpleArmory#298]
Currently, the planner for Mimiron's Head says "Requires 25-man no watchers up".

Since Ulduar can't be done in 25 man difficulty anymore, this is confusing for new players because when you enter the raid, the number 10 is shown at the minimap, which does not match the planner's description.

The planner's description should only say the "no watchers up" condition.

Thanks :)

**Comment by jbryson3** [comment]
Good catch @Otsoko, thanks for reporting. Just made a PR for the fix.

**Comment by seirl** [comment]
Closed in #304
