### ISSUE TITLE
Kyrian mounts

### ISSUE THREAD

**Issue by ItaiDanos** [kevinclement/SimpleArmory#314]
I know there some exclusive Kyrian mounts but i don't see category for that, I see all other 3 covenants but not Kyrian is this intentional?

ty.

**Comment by seirl** [comment]
It's a know issue, there is a work in progress for that by @slemke in #309

**Comment by ItaiDanos** [comment]
ty for the quick replay!

**Comment by seirl** [comment]
Should be fixed in 1e0e352
