### ISSUE TITLE
Mirror of Envious Dreams toy a has wrong icon url

### ISSUE THREAD

**Issue by Kvasi** [kevinclement/SimpleArmory#321]
Should be
https://wow.zamimg.com/images/wow/icons/medium/achievement_guildperk_everyones-a-hero.jpg

**Comment by seirl** [comment]
Which toy are you talking about?

**Comment by Kvasi** [comment]
Mirror of Envious Dreams

**Comment by Kvasi** [comment]
Orophea's Lyre is also wrong, should be 
https://wow.zamimg.com/images/wow/icons/medium/trade_archaeology_carved-harp-of-exotic-wood.jpg

**Comment by seirl** [comment]
Fixed in #326
