### ISSUE TITLE
Oonar's Arm companion missing

### ISSUE THREAD

**Issue by Greymerk** [kevinclement/SimpleArmory#323]
Oonar's Arm pet from a treasure in Maldraxxus appears to be missing from the companions page.

https://www.wowhead.com/item=181164/oonars-arm

**Comment by finnlux** [comment]
Hey can someone clarify where the ID field for companions is supposed to come from? The creatureId and itemId make sense but even looking through past commits I can't tell the intent of the ID field. Is it something internal to SA or does it actually come from Blizzard somewhere?

**Comment by seirl** [comment]
It comes from the new Blizzard API... they decided for some reason to invent a third completely different type of IDs for mounts and pets with no easy way to do the association between them.
In case you were wondering why all the websites using the blizzard API are having trouble keeping up with Shadowlands, this is why.

**Comment by seirl** [comment]
Done in #336
