### ISSUE TITLE
Removed Achievements

### ISSUE THREAD

**Issue by ChapterXXX** [kevinclement/SimpleArmory#327]
Hi,

Exploration achievement 'In the Hot Seat' and PVP 'Forged through Conquest: Shadowlands Season 1' removed at launch 👍 

Cheers
Nicko

**Comment by Alconix** [comment]
Seems like 'In the Hot Seat' is not present in ingame achievements (should be under Exploration > Shadowlands) but is still present on the armory. (maybe hidden achievement ?)

And 'Forged through Conquest: Shadowlands Season 1' seems to have been removed along with the pvp requirement.(https://fr.wowhead.com/news=319737/5-000-conquest-requirement-to-buy-pvp-weapons-will-be-removed)

I opened #331 if you want to remove them

**Comment by seirl** [comment]
Partially fixed in 7dad6a96f4339ceed7d0c42ae70d7cf8a6a2dc39 . In the Hot Seat is actually present in game.
