### ISSUE TITLE
Bonecleaver's Skullboar doesn't exist.

### ISSUE THREAD

**Issue by Roguinaa** [kevinclement/SimpleArmory#340]
As of Prepatch, it hasn't reappeared in the mount journal, and the modelviewer on wowhead also has broken. It is safe to say this mount no longer exists and was likely replaced with the current Sabriel mount drop, the Armored Bonehoof Tauralus.

**Comment by seirl** [comment]
Fixed in f4e8e0de9178e78d048e234ae60ff329110ca644
