### ISSUE TITLE
All covenant mounts visible on one character

### ISSUE THREAD

**Issue by Artrave** [kevinclement/SimpleArmory#343]
I am playing Night Fae exclusively, don't play any alts that would join any other covenant. Although other covenant mounts are visible and are shown as uncollected for my night fae character. Would it be possible to only display covenant appropriate mounts?

**Comment by seirl** [comment]
Not really, we don't have mount filters yet. And I think even if we did, it would be filters on your race/class, not on content you choose not to do. Closing as wontfix.
