### ISSUE TITLE
(Horde) Mount planner hearth to shrine step should be changed to hearth to Orgrimmar 

### ISSUE THREAD

**Issue by Xarano-GIT** [kevinclement/SimpleArmory#345]
Since Shrine now only has a single portal (to Orgrimmar), and Orgrimmar now has a portal room to most locations, it would make sense that the mount planner be changed to skip the step of hearthing to Shrine, only to portal back to Orgrimmar immediately.

Thanks!

**Comment by nzall** [comment]
Not necessarily.

1. The Shrine portal room is the next room over from the Innkeeper. Most classes can cover this in seconds. Meanwhile, the Orgrimmar portal room is so far from the nearest Innkeeper that you need to mount up. You can get from the Shrine Inn to any location reachable by Orgrimmar Portal Room Portal significantly faster than from Orgrimmar Inn.
2. Barely anyone is at Shrine, so you can load in really quickly. The Orgrimmar Inn is in the middle of the busiest part of the city, directly next to the AH and Bank.
3. The Orgrimmar portal to Pandaria leads to Jade Forest, which is quite a long distance away from nearly every mount location. The only mounts that are easier to reach are Elegon and Oondasta. Nearly all other mounts, including the other world bosses, Siege of Orgrimmar, Throne of Thunder are significantly faster to reach from Shrine than from Jade Forest. And even if you need to get to Oondasta or Elegon, just take the Orgrimmar portal and then the Jade Forest portal directly after.

**Comment by seirl** [comment]
Fixed in #447
