### ISSUE TITLE
Snowstorm mount doenst show up

### ISSUE THREAD

**Issue by scrapmuffin** [kevinclement/SimpleArmory#349]
currently the mount snowstorm isnt showing up in the collection its the mount you can buy for the 30th anniversary in the heroic or epic pack
wandering ancient isnt showing up either

**Comment by CharmCityNorth** [comment]
Lucky Yun also not showing up in the mount list.

**Comment by syko8640** [comment]
Also missing wandering ancient mount. Snowstorm should be in the blizzcon section with the boat and the original bear

**Comment by seirl** [comment]
This was a blizzard issue. All these mounts properly show up now.
