### ISSUE TITLE
Hopecrusher Gargon not showing on all my characters.

### ISSUE THREAD

**Issue by Lyera85** [kevinclement/SimpleArmory#351]
Just obtained this on my Venthyr-character. It shows up in his profile but not in three other character in different covenant. The Necrolord character can't see it. Night Fae and Kyrian is solved. 

Venthyr-character (where mount is shown): https://simplearmory.com/#/eu/alonsus/sethil/collectable/mounts

Necrolord-character (not showing): https://simplearmory.com/#/eu/alonsus/meryssa/collectable/mounts

**Comment by seirl** [comment]
This is very likely not something we can do anything about, and is happening on the Blizzard side. Try to log in and out of the other characters a few times, then wait for like a day or so to confirm that the problem persists. Closing in the meantime as it's very unlikely to be a problem on our side.
