### ISSUE TITLE
Site is accurate on phone and laptop, but isn't on PC (misses my newest mounts etc)

### ISSUE THREAD

**Issue by WendyMarilyn** [kevinclement/SimpleArmory#355]
Hi there,

For some reason the website doesn't refresh on my PC. I've tried all the main 'refresh' ways like alt+f5 and deleting cache by hand. Because of this, I can't see the newest things I have collected; I've got 4 new mounts but after 3 days I still can't see them on the site. But, on my phone and my laptop I can see them... Also, when I try to refresh the page, it goes blank and I need to restart the whole site. Does anybody have experience with this?

Kind regards

**Comment by seirl** [comment]
Does it also happen if you open it in a private window?

**Comment by WendyMarilyn** [comment]
> Does it also happen if you open it in a private window?

Wow, no, it doesn't. If I open in a private window I do see my mounts just like on my phone or laptop :O

**Comment by seirl** [comment]
Then it's a cache issue from your browser. Not sure why deleting the cache by hand wouldn't fix it though, but I don't know if we can do something about it.

**Comment by WendyMarilyn** [comment]
> Then it's a cache issue from your browser. Not sure why deleting the cache by hand wouldn't fix it though, but I don't know if we can do something about it.

Private window works fine for now, maybe the problem will fix itself someday :P Thanks anyway for the help :D
