### ISSUE TITLE
Castle Vain in wrong Category

### ISSUE THREAD

**Issue by Zerbersteras** [kevinclement/SimpleArmory#359]
The Achievement Castel Vain (acquired by completing a full Transmog Set from Castle Nathria) is listed in BFA instead of a new (missing) Category "Shadowlands"
![image](https://user-images.githubusercontent.com/57775822/115940293-3755ec80-a4a1-11eb-9b60-d0a0b9aa76b1.png)

**Comment by seirl** [comment]
Fixed in #385
