### ISSUE TITLE
Covenant Specific Mounts - Rare Spawns

### ISSUE THREAD

**Issue by Dakke96** [kevinclement/SimpleArmory#363]
The Mount Predatory Plagueroc is listed under Rare Spawns in Shadowlands, but it is covenant specific, and should be listed under the respectful Covenant Necrolord, as Hopecrusher is listed under Venthyr :)

Edit: Same goes for Wild Glimmerfur Prowler from Valfir, and Horrid Dreadwing from Harika.

**Comment by seirl** [comment]
Fixed in #374
