### ISSUE TITLE
Add obtainable Feats of Strength?

### ISSUE THREAD

**Issue by Alexxfreeland** [kevinclement/SimpleArmory#367]
It would be nice to see feats of strength that are still obtainable in the game. Mount feats and reputation feats such as Insane would be nice to see, and view which ones you are missing.

**Comment by maxdekrieger** [comment]
@seirl This was added in https://github.com/kevinclement/SimpleArmory/pull/459

**Comment by SolestialDev** [comment]
Added full functionality for this in #644 (toggle to view obtainable FoS is found under Settings)
