### ISSUE TITLE
Planner gives impossible advice.

### ISSUE THREAD

**Issue by Ketrel** [kevinclement/SimpleArmory#369]
I checked what the mount planner showed for kicks and it's giving impossible advice.

1 | Start off in Orgrimmar | &nbsp; | Make sure you have hearth set to shrine
-- | -- | -- | --
2 | Portal to Orgrimmar | &nbsp; | &nbsp;
3 | Portal to Blasted Lands | &nbsp; | &nbsp;
4 | Fly to Deadwind Pass

Step 3 isn't possible as there is no portal to blasted lands and hasn't been for quite a long time.

**Comment by seirl** [comment]
Fixed in #447
