### ISSUE TITLE
Toys I collected don't show

### ISSUE THREAD

**Issue by aienia** [kevinclement/SimpleArmory#371]
I collected a few toys the last 2-3 days but they wont show up in my collection. I also collected 2 mounts  (after the toys) and they showed up so my guess is that there is some bug with toys only?

**Comment by seirl** [comment]
Do you update the toys manually using the addon?

**Comment by aienia** [comment]
> Do you update the toys manually using the addon?

What do you mean? None of my other toys did I update manually and I can´t find where I would do that.
