### ISSUE TITLE
Pandaria mount missing

### ISSUE THREAD

**Issue by aienia** [kevinclement/SimpleArmory#372]
I can´t find the mount "[Reins of the Ashhide Mushan Beast](https://www.wowhead.com/item=103638/reins-of-the-ashhide-mushan-beast#comments)" in the pandaria section, have not checked if it is elsewhere but you can buy it from vendor "[Speaker Gulan](https://www.wowhead.com/npc=73307/speaker-gulan)" in Timeless Isle.

**Comment by seirl** [comment]
It's in the PVP category.
