### ISSUE TITLE
Intact Aquilon Core

### ISSUE THREAD

**Issue by jessli9** [kevinclement/SimpleArmory#380]
Hi, I got the quest item Intact Aquilon Core which rewards Foresworn Aquilon mount but I didnt get a screenshot :( first time this happened to me and the addon is updated to latest version it is not marked as found it just tracked kill

**Comment by seirl** [comment]
You are confusing with something else, the SimpleArmory addon doesn't take screenshots. You're maybe thinking of Rarity.

**Comment by jessli9** [comment]
Oh my gosh so sorry :)
