### ISSUE TITLE
Battle Pets The Maw/Korthia 9.1

### ISSUE THREAD

**Issue by zhyphys** [kevinclement/SimpleArmory#384]
Hi, i think that all new Battle Pets for Maw and Korthia and possibly other zones (Desmotereon) on simplearmory are still missing, can you check that? Best regards

**Comment by seirl** [comment]
Duplicate of #379

**Comment by zhyphys** [comment]
can this be fixed?

Am So., 8. Aug. 2021 um 14:12 Uhr schrieb Antoine Pietri <
***@***.***>:
