### ISSUE TITLE
Spirit of the Spring - Pet

### ISSUE THREAD

**Issue by aienia** [kevinclement/SimpleArmory#387]
Hi, I got this pet in a Pandaria raid a couple of months ago and it's still not in the pandaria section! Maybe add it to the "raid"pets? :) (spirit of the spring is the name of the pet!)

**Comment by seirl** [comment]
It's already in Raiding with Leashes: 
![image](https://user-images.githubusercontent.com/4927883/132929404-d1e100cd-1ce1-4707-b454-6a27030ebc71.png)
