### ISSUE TITLE
"Field medic" title is missed in title list

### ISSUE THREAD

**Issue by Rauko** [kevinclement/SimpleArmory#399]
achieve to track https://www.wowhead.com/achievement=11139

**Comment by finnlux** [comment]
I don't think this is obtainable any more. I left out all the unobtainable ones. I think that's how the other collections work?

**Comment by seirl** [comment]
@finnlux No, we include the unobtainable ones but just add `"notObtainable": true` in the JSON to show them only to people who already have them.

Let's move this discussion to #400
