### ISSUE TITLE
Legion Class Mount Druid missing

### ISSUE THREAD

**Issue by zhyphys** [kevinclement/SimpleArmory#402]
here is the comment from Blizzard on this, will this be added then?

Good news! The  Archdruid's Lunarwing Form operates like a shapeshift in terms of benefits (instant cast, immune to polymorph, etc.) but also counts as an additional mount in your mount journal.

**Comment by seirl** [comment]
I don't think it actually is in the mount journal: https://wow.tools/dbc/?dbc=mount&build=9.1.5.40622#page=1&search=Lunarwing
Maybe it counts for statistics purposes, but it doesn't seem to be returned by the API, so I don't think we can do much about that.
