### ISSUE TITLE
Missing Enraged Poultrid battle pet

### ISSUE THREAD

**Issue by aaronincincy** [kevinclement/SimpleArmory#418]
There is another battle pet in Zereth Mortis that I'm assuming isn't coming up during the dataimporter, the Enraged Poultrid. I don't know if it should be included in the standard Zereth Mortis collection or not, as it doesn't spawn naturally.  You have to find a level 1 critter Agitated Poultrid, target it and /chicken at it and it will transform into the battle pet where you can fight it and capture it.

I've captured what I think is some of the data for it should be below but it would be good to get some verification:

```
          {
            "ID": ???,
            "creatureId": 183285,
            "icon": "inv_progenitorchicken_yellow",
            "name": "Enraged Poultrid"
          }
```

[Wowhead](https://www.wowhead.com/npc=183285/enraged-poultrid)
[Xu-Fu's Pet Guides](https://wow-petguide.com/News/338/Patch_9.2_Compilation_Article_-_Updated:_26_Feb_22_2021-11-22&ScrollTo=2.2-Pet_Battles_21_) article where I initially found it.

I have captured this pet, so if you want to use I can confirm that I've captured this pet, so if you want to use https://simplearmory.com/#/us/durotan/shwang/collectable/battlepets as a test profile it should be there.

**Comment by seirl** [comment]
Found the problem with wild pets being ignored by the dataimporter, it's fixed in a4254a2
