### ISSUE TITLE
legion class hall mounts

### ISSUE THREAD

**Issue by lamikral04** [kevinclement/SimpleArmory#420]
I did on my alt /paladin- Lamisudruh/ legion class hall campaign and got my mounts, but when i open simple armory on my main /shaman- Lamikrall/ it doesnt show those mounts only class hall mount for shaman. But when open simple armory on my alt it shows both mount for shaman and those for paladin

**Comment by seirl** [comment]
It works for me. Remember that you need to relog on your main character for it to update your mounts.
If it still doesn't work after doing that and waiting for a bit, can you give us a link to your character?
