### ISSUE TITLE
Web site not working, please fix it

### ISSUE THREAD

**Issue by space-guard** [kevinclement/SimpleArmory#427]
![image](https://user-images.githubusercontent.com/70911825/163722060-32dd1cda-7f5b-4691-9d28-7038be0adc0b.png)
This hapends last few days when i enter to website, itryed few characters and realms.

**Comment by maxdekrieger** [comment]
Hi @space-guard, could you provide some more details please? What character are you trying to load (region + server name + character name)?

**Comment by space-guard** [comment]
Hi [maxdekrieger](https://github.com/maxdekrieger)

> Hi @space-guard, could you provide some more details please? What character are you trying to load (region + server name + character name)?

https://simplearmory.com/#/eu/howling-fjord/будилдо
It russian realm

Also tryed German character
https://simplearmory.com/#/eu/malygos/dannyd

i tryed in opera, chrome, firefox, edge, tryed with vpn and without vpn

**Comment by maxdekrieger** [comment]
Hmm that's odd, both characters work fine for me... (see screenshot attached). Do you get any errors in the browser console (F12) when you are loading the page?

![screenshot](https://user-images.githubusercontent.com/25172452/163799134-af17ccf3-b51c-451e-89ba-2302d2290526.png)

**Comment by space-guard** [comment]
![image](https://user-images.githubusercontent.com/70911825/163828393-5ce436e0-bc8b-4809-803f-d44bc1d48e10.png)
Yes, have errors

**Comment by space-guard** [comment]
I think you can close it, after reboot pc it resolve. idk why this problem might occur
