### ISSUE TITLE
Missing/obsolete titles

### ISSUE THREAD

**Issue by TheKrowi** [kevinclement/SimpleArmory#430]
#### PVP - World PVP
- Deathbringer: https://www.wowhead.com/achievement=14520/deathbringer

#### Shadowlands - Raids
- Guardian of the Pattern: https://www.wowhead.com/achievement=15489/mythic-the-jailer

#### PvP - Ranked PVP
- High Warlord: https://www.wowhead.com/achievement=5356/high-warlord

**Comment by maxdekrieger** [comment]
I'm working on the missing titles, in combination with #400.

Are we sure the Deathbringer title is no longer in the game? I didn't see an official source yet saying it's unobtainable.

**Comment by TheKrowi** [comment]
Pretty sure. Check this: https://wow.tools/dbc/diff.php?dbc=achievement&old=9.0.1.36216&new=9.0.2.36401.

If you show 1000 entries, scroll down to the red parts. There Deathbringer is removed.

**Comment by maxdekrieger** [comment]
Wow indeed, good catch! Added a new commit to my latest PR

**Comment by maxdekrieger** [comment]
@TheKrowi This was fixed in the latest PR merge :) Feel free to close
