### ISSUE TITLE
Mounts didnt updating

### ISSUE THREAD

**Issue by Rudyfive5** [kevinclement/SimpleArmory#431]
Hi,

Iam back playing from 6 months pause and my new mounts didnt showing. Any tips for repair? Thanks

**Comment by seirl** [comment]
Could you please send us a link to your profile?

**Comment by Rudyfive5** [comment]
ctrl+ f5 even ctrl + shift + f5 didnt help but clearing cookies and cache was, thanks for support, everything showing right now

**Comment by maxdekrieger** [comment]
Ahh awesome, feel free to close the issue :)
