### ISSUE TITLE
Cost of buying Breezestrider Stallion is wrong

### ISSUE THREAD

**Issue by solkarnar** [kevinclement/SimpleArmory#449]
https://www.wowhead.com/item=116775/breezestrider-stallion#sold-by

The cost of buying the mount has been changed from [5000 Apexis crystals + 5000g] to [100 Marks of Honor + 5000g].

**Comment by seirl** [comment]
Thanks for the report. Unfortunately this is a wowhead issue, we just use their tooltips but we don't store this information ourselves. You'll need to make a bug report to their discord. As you can see on the page you linked, they show the cost in apexis crystals.
