### ISSUE TITLE
PETS, mounts ETC Warcraft

### ISSUE THREAD

**Issue by Pwayne55** [kevinclement/SimpleArmory#453]
iv noticed that it says i have all the pets in meldraxes or on another map yet i know im m issing a few rare drop ones, yet there is no empty box for where that pet will be on my profile. i should beable to hover over the empty box and see what im missing and how to get it like others. can this get fixed please and thank you

**Comment by seirl** [comment]
Sorry but you're gonna need to be way more specific than that. How do you want us to guess which pets you're talking about?

**Comment by seirl** [comment]
Closed, not actionable.
