### ISSUE TITLE
Allied Races Mounts

### ISSUE THREAD

**Issue by zhyphys** [kevinclement/SimpleArmory#461]
can you add please faction related mounts from allied races such as Grimhowl for Dark Iron Dwarves which is a bit of a hidden mount, i'd assume very little people have noticed it exists.

**Comment by seirl** [comment]
It's already there. BFA > Allied Races. The categorization isn't ideal but the mount is there.

**Comment by zhyphys** [comment]
found it

Am Mo., 19. Sept. 2022 um 22:41 Uhr schrieb Kuehl, Nikolai <
***@***.***>:

**Comment by zhyphys** [comment]
ok, sorry, but i couldn't find Grimhowl as a mount

Am Mo., 19. Sept. 2022 um 22:04 Uhr schrieb Antoine Pietri <
***@***.***>:

**Comment by seirl** [comment]
...? It's the last item in the BFA > Allied Races category, like I said before
+.

![grimhowl](https://user-images.githubusercontent.com/4927883/195062199-63316d46-bb31-4f50-8dc5-74c8c81d55ba.png)
