### ISSUE TITLE
Some Legion Class Hall pets are miscategorized as Draenor Mission Table

### ISSUE THREAD

**Issue by Unclevinny** [kevinclement/SimpleArmory#462]
Go to, for example: https://simplearmory.com/#/us/khadgar/vild/collectable/companions
Look at the section Warlords of Draenor / Table Missions

Firebat Pup and Corgnelius are listed there, but they should be listed under Legion / Order Hall

**Comment by Leomelati** [comment]
@seirl, Can you close this one?

**Comment by seirl** [comment]
Fixed in #463
