### ISSUE TITLE
URL Link Errors for Items linked to WoWHead

### ISSUE THREAD

**Issue by Kriptoker** [kevinclement/SimpleArmory#471]
Hello,

The Links to view, say mounts, on WoWHead seem to not work correclty (I have tried on multiple devices/browsers).

The links are set as follows:
https://wowhead.com/item=186643

This link does not work in this format. For the URL to work, I have to add **www.** to the URL: https://www.wowhead.com/item=186643

**Comment by seirl** [comment]
The link without www works for me.

**Comment by Kriptoker** [comment]
Ah ok, must be something on my end then, maybe a DNS issue or something. I will close this then, since it appears to be working for others.
