### ISSUE TITLE
Otterworldly Ottuk Carrier

### ISSUE THREAD

**Issue by JRamos-23** [kevinclement/SimpleArmory#472]
Hello there

I'm writing this because one recent mount is missing from the achievements section: otterworldly ottuk carrier 

https://www.wowhead.com/item=198654/otterworldly-ottuk-carrier

Thanks for your great job!

**Comment by seirl** [comment]
That's expected, we haven't imported data from the Dragonflight build yet.

**Comment by Leomelati** [comment]
@seirl Can you close this one?
