### ISSUE TITLE
When Dragonflight???

### ISSUE THREAD

**Issue by zhyphys** [kevinclement/SimpleArmory#473]
When will Dragonflight Mounts/Pets/Toys/Collectibles like the new dracthyr racials etc be added????

**Comment by seirl** [comment]
Whenever someone adds them, which can usually take a bit of time. Please keep in mind that this is an open source project maintained by volunteers on their spare time, they don't owe you work.

**Comment by zhyphys** [comment]
it might be open source, but you could try and get ads on the site, cause
there are probably thousands of clicks every week.
The fact that its not yet more commercialized is not caused by users like
me.

Am Mi., 23. Nov. 2022 um 11:40 Uhr schrieb Antoine Pietri <
***@***.***>:

**Comment by seirl** [comment]
Even if we did have ads, you still wouldn't be entitled to our time.
