### ISSUE TITLE
Enhancements to Battle Pet + Companion overviews

### ISSUE THREAD

**Issue by LyaVanLou** [kevinclement/SimpleArmory#480]
Let me start by saying that I realize the following suggestions would usually be seperated into multiple issues for better tracking, but since they're closely related, I opted to consolidate them.

**The issue I stumbled over** 
Earlier today I wanted to take a look at my progression for catching battle pets across the world, with the goal being having caught every battle pet in their 'rare' variety, because they might be needed for battle strategies, etc. While I can't speak for the majority of collectors, I assume most people who actively collect battle pets (and companions) do the same.
While looking for where to start, I stumbled over the display of my Unborn Val'kyr. Reason for that being that it's displaying this pet as being collected in their 'very common' (grey) variant, while I *know* that I own a level 25 rare one - additionally to a very common one at level 21 which is still waiting for it's upgrade (see screenshots at the end). For me personally, it doesn't make sense to prioritize displaying the lower value pet here, which lead me to the following suggestions.

**Options to prioritize displaying Battle Pets by level and/or rarity**
As not everyone might have the same priorities I have, I figured the most sensible solution would be adding options for which pets should be prioritized for displaying the collection status. Having the choice between 'any', 'by level' and 'by rarity' should suffice to please everyone.

**Displaying all owned Battle Pets**
A working alternative for the options above would be simply displaying all caught pets, although that would probably mean a restructuring of how the displays work in general. (Displaying additional bars for the rarities underneath the icons shouldn't be difficult, but the more detailed view with 'Show levels and breed' would require more work/decision making.)

**Aligning displays of Battle Pets and Companions**
And finally, people might care about the above for levelable Companions, too, so aligning the displays would be fantastic. This would enable collectors to utilize the Companions page to decide where to use their upgrade stones and/or what to level next, even if it's not a "caught" battle pet.

**Screenshots**
![image](https://user-images.githubusercontent.com/56847157/207001284-ef3a3ec2-9956-4a70-b176-3b39d6d8d8d5.png)
Display of the Battle Pet "Unborn Val'kyr" on [my main's profile](https://simplearmory.com/#/eu/todeswache/cer%C3%A9s/collectable/battlepets)

![image](https://user-images.githubusercontent.com/56847157/207001608-14f6fb55-3c90-42a9-87a8-0733c914a665.png)
"Unborn Val'kyr" pets in my pet journal

**Comment by Leomelati** [comment]
Hey @LyaVanLou, thank you for opening this issue!

`it doesn't make sense to prioritize displaying the lower value pet here`
I agree with that. It was a bug that we were replacing the higher-quality pets with the lower ones depending on the armory's response. I don't know if it was an edge case or was occurring at another place, but it should be fixed at the next release.

About the suggestion, all of them would require considerable work to release. I don't know which one @seirl, @kevinclement, or @maxdekrieger would prefer. Which one do you guys prefer?

**Comment by Leomelati** [comment]
@maxdekrieger or @seirl, can one of you guys close this one? It was merged some time ago.
