### ISSUE TITLE
Magmashell

### ISSUE THREAD

**Issue by JRamos-23** [kevinclement/SimpleArmory#483]
Hello!

This mount https://www.wowhead.com/item=192777/magmashell  doesn't appear on Dragonflight section.

Thanks in advance

**Comment by maxdekrieger** [comment]
After some investigation, it is in there, but we set it to `notObtainable: true`, meaning that it will only appear when you actually have it. The reason being that at the time of categorizing the mounts, it was still unknown where to get this mount and if it was obtainable at all.

Thanks for pointing out that the source is known now, will be fixed soon :)
