### ISSUE TITLE
Mount Otto

### ISSUE THREAD

**Issue by JRamos-23** [kevinclement/SimpleArmory#485]
Hi there !

Secret mount Otto https://www.wowhead.com/item=198870/otto has been found. 

Guide: https://www.wowhead.com/news/otto-mount-found-fish-around-the-dragon-isles-for-otter-mount-330658

Can you please add it to dragonflight mount section? It can be obtained near the obsidian citadel.

Thanks in advance

**Comment by Leomelati** [comment]
Hey @JRamos-23,

Thank you for pointing this out!
You can check the progress of it at #486.

**Comment by Leomelati** [comment]
@seirl Can you close this one?
