### ISSUE TITLE
Toy not showing

### ISSUE THREAD

**Issue by aienia** [kevinclement/SimpleArmory#487]
Hello,

I just noticed that my "Silver-Plated Turkey Shooter" doesn't show up as collected on simplearmory. 
If you want me to send some evidence like a screenshot or something, let me know :)

Best regards,
Aienia

**Comment by aienia** [comment]
Okay so after looking a bit more on my toys I see now that there is a bunch of toys missing from my simplearmory. Maybe this is a knows issue already. Just wanted to let you know.

**Comment by Leomelati** [comment]
Hey @aienia,

Thank you for opening this issue.
We were missing the Dragonflight toys, I think we have all of them covered now with this PR #489

**Comment by aienia** [comment]
Hello! 
Im not talking about the DF toys, for me alot of SL toys are missing, and world event toys.

**Comment by aienia** [comment]
Ingame I have 287/772 toys, and on the website I have 189/733 toys. so almost 100 of my toys are not showing

**Comment by maxdekrieger** [comment]
Just to be sure, are you using the SimpleArmory addon and exporting the toys in-game and importing them to SimpleArmory?

**Comment by maxdekrieger** [comment]
@aienia did the reply above resolve your issue? If yes, feel free to close the issue :)
