### ISSUE TITLE
Achievements > Quests > Loremaster

### ISSUE THREAD

**Issue by BlofeldsCat** [kevinclement/SimpleArmory#488]
I'm checking my character (Goresh @ The Shatar) and none of the Loremaster titles are showing as achieved however all the sections are completed on my character and show as completed on the mouse over.

**Comment by BlofeldsCat** [comment]
I've noticed quite a few more like this....

Achievements > Exploration > All the zone one like Eastern Kingdoms Explorerer and Universal Explorer
Achievements > Exploration > Draenor Pathfinder
Achievements > Exploration > BfA Pathfinder part 1 and part 2 etc

Is this a blizzard issue?

**Comment by BlofeldsCat** [comment]
I turned off Display only Character Achievements and it fixed it even though Goresh had independently achieved those goals.

Weird.

**Comment by seirl** [comment]
It's not weird, it's expected behavior. The Blizzard API doesn't return account achievements if you have this setting enabled. Nothing we can do about it. Glad to know you figured it out!
