### ISSUE TITLE
Mounts not working. Leads to "Uh oh! You no get candle..."

### ISSUE THREAD

**Issue by achidler** [kevinclement/SimpleArmory#490]
The mounts section seems to be dead today (01.01.2023) 
![Screenshot 2023-01-01 175229](https://user-images.githubusercontent.com/63874511/210178941-a50998d3-1bd8-4a96-9724-404285a96813.jpg)

**Comment by maxdekrieger** [comment]
@achidler are you still having this issue?

**Comment by seirl** [comment]
Please provide a link to your profile, with the censored character name it's impossible to debug :-)
