### ISSUE TITLE
Achievements aren't updating after last update

### ISSUE THREAD

**Issue by gavintodd** [kevinclement/SimpleArmory#499]
I completed a couple achievements the other day and have logged in and out multiple times and it isn't showing on the site as completed.

**Comment by cassetto** [comment]
confirmed, running in the same issue. I'll keep it monitored with an achievement I earned today.

**Comment by AWMarin12** [comment]
Do you know if the achievements are showing up in the armory website (https://worldofwarcraft.com/en-us/character/us/[server]/[character name])?

**Comment by gavintodd** [comment]
Just checked and I think they aren't updating on armory side either.

**Comment by gavintodd** [comment]
Looks like blizzard fixed it and is working as of this morning.
