### ISSUE TITLE
Missing 10.0.7 mounts

### ISSUE THREAD

**Issue by larryeltee** [kevinclement/SimpleArmory#505]
Missing the new mounts from the 10.0.7 patch. May be missing some, but here are the one I know of:

**- Goeey Snailemental** (https://www.wowhead.com/ptr-2/item=192785/gooey-snailemental) from **Froststone Vault Primal Storm** event boss
**- Mossy Mammoth** (https://www.wowhead.com/ptr-2/item=192790/mossy-mammoth) from a 6 step combination of items containted in the **Zskera Vault** treasures
**- Ancient Salamanther** (https://www.wowhead.com/item=192772/ancient-salamanther) from **Rares of The Forbidden Reach**
**- Nobble Bruffalon** (https://www.wowhead.com/ptr-2/item=204382/noble-bruffalon) **vendor purchase** of 100k Elemental Overflow

**Comment by ThePrimoris** [comment]
I went and added the mounts to mounts.json and can drop a pull request for this if needed.

**Comment by medavidcook** [comment]
Its also not showing the new achievements

**Comment by Leomelati** [comment]
Opened PR to update achievements, pets, titles, and toys #507

**Comment by Bukama** [comment]
Mounts were added with #506, but (at least for me) the "Noble Bruffalon" is not tracked, but I can't find out why as the spellid and itemid in the PR are identical to those on wowhead.

Armory was updated - the other mount I got days after (to be exactly: yesteday) the Bruffalon is already been tracked.

**Comment by GTmAster** [comment]
> Mounts were added with #506, but (at least for me) the "Noble Bruffalon" is not tracked, but I can't find out why as the spellid and itemid in the PR are identical to those on wowhead.
Same to me, Brufallon is not tracked. In official armory it is stated as collected. Probably game data API hiccup.

**Comment by seirl** [comment]
Fixed, ran the dataimporter again.
