### ISSUE TITLE
Forbidden Reach Pet Battle Pet Rewards

### ISSUE THREAD

**Issue by TitsMcGee84** [kevinclement/SimpleArmory#519]
The 4 pets awarsded by defeating the Rare version of the Pet Battles (Flow, Tremblor, Wildfire & Vortex) are not updating as collected on my SA profile. I have, however, collected all 4, and even levelled a couple. 

I first noticed this a couple days ago when the new 10.0.7 additions were loaded to SA, but waited to see if it would resolve itself, as I know sometimes it takes time for newer collected items to hit the SA website. 

I did notice that the markers for all 4 pets point to the untameable version that is actually battled, and not the collectable version. I wonder if this also means the ID for the pet is wrong, thus not reflecting the pets as "collected"?

**Comment by Ophidon** [comment]
They actually are there and do show as collected, as the last 4 in the Dragonflight quest category. The other listings for them under the forbidden reach category are thus duplicates, and indeed also do not work.

Personally I would suggest moving the currently working slots for them from Quest to the Forbidden Reach category as the duplicate entries should be removed one way or the other, and of the two categories, forbidden reach does seem better.

**Comment by TitsMcGee84** [comment]
Many thanks! I hadn't noticed them as collected on the Quest category -
clearly I should have finished my coffee before opening the bug report. I
appreciate your extra info! :)
