### ISSUE TITLE
Incorrect (multiple) costs for mounts with at least two different items

### ISSUE THREAD

**Issue by Bukama** [kevinclement/SimpleArmory#531]
The costs for mounts, which costs at least two different items, are shown multiple times. One example:

![image](https://github.com/kevinclement/SimpleArmory/assets/4354359/90e3442b-79ed-4031-9bbe-cbfca89cc7b1)

For mounts with only one item, it seems to correct.

**Comment by seirl** [comment]
Hello! Thanks for reporting, but this is a Wowhead bug. We don't control what's displayed on the tooltips, so there's nothing we can do about it. Closing.
