### ISSUE TITLE
Collectable -> Titles won't load

### ISSUE THREAD

**Issue by higginz** [kevinclement/SimpleArmory#536]
It only affects my main character:

https://simplearmory.com/#/eu/blackrock/williamz/collectable/titles

On my alt it loads as aspected:

https://simplearmory.com/#/eu/blackrock/williamzz/collectable/titles

**Comment by maxdekrieger** [comment]
Hi! Hmm that's annoying indeed.

SimpleArmory fetches your character's data from armorystats.info and the response seems to be inconsistent between your main and your alt. The data belonging to your main does not have the `titles` key in its response while that of your alt does (see screenshots below).

![response_main](https://github.com/kevinclement/SimpleArmory/assets/25172452/ffcd9dee-3149-4e7d-8005-1e2274cb1523)
![response_alt](https://github.com/kevinclement/SimpleArmory/assets/25172452/49435726-a241-48e7-817c-30490b43d387)

I don't know how to further investigate this. Can we report this somewhere to armorystats? (@seirl)

**Comment by kevinclement** [comment]
Thats odd that your alt works but your main doesn't.  Armorystats is just a proxy to the blizzard api with a shared key so I can still load the armory info without having to login, its a workaround, but shouldn't be introducing anything here.

Can you confirm that you don't have "Shared Game Data" disabled at [https://account.battle.net/privacy](https://account.battle.net/privacy).
![image](https://github.com/kevinclement/SimpleArmory/assets/132959/f11b3601-9dae-4f4c-b029-dff30e7689c1)

It probably is enabled if your alt is working.

Can you also confirm, in the game, under Options->Social->Display Only Character Achievements to Others.  Make sure that isn't checked.

![image](https://github.com/kevinclement/SimpleArmory/assets/132959/6ed07c9f-bea9-42dd-b83a-0f3c77c16e98)

Closing ticket for now, feel free to re-open if you find out anything more.
