### ISSUE TITLE
Collectables -> Titles -> Dragonflight -> Smelly

### ISSUE THREAD

**Issue by strchsr** [kevinclement/SimpleArmory#545]
The achievement for "Smelly" is currently showing the achievement "It's In The Mix" from Shadowlands rather than "There's No Place Like Loamm", which is granted upon reaching Renown 20 with the Niffen, as well as the title.

**Comment by maxdekrieger** [comment]
Hi, nice catch! Updated this in PR #544. I assume you were looking at the deploy preview? On the live version of SimpleArmory it is correctly categorized but in my PR I messed it up :)

**Comment by maxdekrieger** [comment]
@seirl this is fixed since the merging of the mentioned PR

**Comment by kevinclement** [comment]
sounds like this was fixed, if not let me know the specifics of what is broken in latest live site.
