### ISSUE TITLE
Miscategorizations & Improvement Suggetions

### ISSUE THREAD

**Issue by F0ri0n** [kevinclement/SimpleArmory#549]
Hi there,
here are a couple of recent miscategorizations that I noticed and some improvement suggestions that I would like to propose. 
Thanks for your continued work on this excellent site!
(Please let me know if it is better to create separate issues for these proposals)

-----------

The source of the Armored Siege Kodo mount is currently still listed under:
 
Mounts -> Other -> Unknown
 
When it is in fact a store mount. The source should be:
 
Mounts -> Promotion -> Blizzard Store
 
https://www.wowhead.com/item=190636/armored-siege-kodo
 
-----------
 
The source of the Crushhoof pet is currently listed under:
 
Pets -> Promotional -> Trading Post
 
When it is also acquired via the store. The source should be:
 
Pets -> Promotional -> Blizzard Store
 
https://www.wowhead.com/item=190608/crushhoof
 
-----------
 
The 3 achievements for collecting Flightstones are currently listed under:
 
Achievements -> Exploration -> Dragon Isles -> Zaralek Cavern
 
As they are not specifically related to Zaralek Cavern and will likely continue to be a thing in 10.2, my suggestion would be to create a new subcategory:
 
Achievements -> Exploration -> Dragon Isles -> Flightstones
 
https://www.wowhead.com/achievement=17830/stones-cant-fly
https://www.wowhead.com/achievement=17977/stones-can-try-to-fly
https://www.wowhead.com/achievement=17978/stones-can-fly
 
-----------
 
The achievements "Draconically Superior" and "Draconically Epic" currently link to the wrong Wowhead IDs
 
Achievements -> Character -> Items
 
Current links:
https://www.wowhead.com/achievement=18365/hidden-do-not-use-draconically-superior
https://www.wowhead.com/achievement=18366/hidden-do-not-use-draconically-epic
 
Correct links:
https://www.wowhead.com/achievement=18976/draconically-superior
https://www.wowhead.com/achievement=18977/draconically-epic
 
-----------
 
With more and more Dragon Races being added, my suggestion would be to change the order structure from the current "race type" to the "race zone". So for example:
 
Achievements -> Expansion Features -> Dragonriding -> Dragon Isles
Achievements -> Expansion Features -> Dragonriding -> Forbidden Reach
Achievements -> Expansion Features -> Dragonriding -> Zaralek Cavern
Achievements -> Expansion Features -> Dragonriding -> Kalimdor
Achievements -> Expansion Features -> Dragonriding -> Eastern Kingdoms
 
Each of these subcategories would then include all Normal, Advanced, Reverse, Challenge and Completionist achievements for the respective zone. I think this would improve the overview.

**Comment by maxdekrieger** [comment]
Hi @F0ri0n, thanks for your excellent suggestions; I agree with all of them.

I'm working on adding the 10.1.7 data as we speak and will start doing these after, or feel free to make a PR yourself if you have the time :)

**Comment by Leomelati** [comment]
@maxdekrieger @seirl
Can we close this one?

**Comment by kevinclement** [comment]
Thanks for reporting this, I know its been open a while, but just getting caught up.  I verified all the issues you called out have been fixed.  I just recently re-categorized the races, so thats fixed now too.  Let me know if I missed something.  Thanks.

[x] Armored Siege Kodo
[x] Crushhoof
[x] Flightstones
[x] Items
[x] Races broken out into categories
