### ISSUE TITLE
new achievements 10.1.7?

### ISSUE THREAD

**Issue by ttag12** [kevinclement/SimpleArmory#554]
Hi, some parts of 10.1.7 have been added, others not, eg new Profession achievements?
Are these different data records, or why is that separate it seems?
Thx

**Comment by maxdekrieger** [comment]
Hi, I'm still working on categorizing the new achievements. You can expect a new release soon(tm).

**Comment by ttag12** [comment]
thx! Great to know.

**Comment by ttag12** [comment]
> Hi, I'm still working on categorizing the new achievements. You can expect a new release soon(tm).

? still no update? :(

**Comment by ttag12** [comment]
can you post the link to the DEV site?

**Comment by maxdekrieger** [comment]
https://deploy-preview-556--simplearmory.netlify.app/#/

**Comment by tatatada** [comment]
Achievements Professions => https://wowhead.com/achievement=18778 
=> Tooltip is not wide enough

Companions => Promotional => The following picture Links are broken 
=> https://wowhead.com/battle-pet/3475
=> https://wowhead.com/battle-pet/2780
=> https://wowhead.com/battle-pet/2890

Mounts => Promotion => The following picture Links are broken 
https://wowhead.com/spell=308087
https://wowhead.com/spell=381529
https://wowhead.com/item=173297
https://wowhead.com/item=173299

Achievements Reputation => Dragonflight => The following picture Link is broken 
https://wowhead.com/achievement=16600
