### ISSUE TITLE
Bad URLs or something else?

### ISSUE THREAD

**Issue by RAtwood90** [kevinclement/SimpleArmory#555]
Hello, couldn't find any related so please close if it's an duplicate.

But since an bit for few Mounts i just see the "Cutted Paper" Icon for bad URL.

It's cause WoWHead is missing their Pictures if you click the Link.

But you may knowing an Workaround for that Problem.

Reins of the Explorer's Dunetrekker as Example.

Thanks!

**Comment by Leomelati** [comment]
Hey @RAtwood90, thank you for opening this one!

I just reported to Wowhead that the following mounts are missing their icons:
 - [Lucky Yun](https://www.wowhead.com/spell=308087/lucky-yun)
 - [Telix the Stormhorn](https://www.wowhead.com/spell=381529/telix-the-stormhorn)
 - [Reins of the Explorer's Dunetrekker](https://www.wowhead.com/item=173297/reins-of-the-explorers-dunetrekker)
 - [Keys to the Explorer's Jungle Hopper](https://www.wowhead.com/item=173299/keys-to-the-explorers-jungle-hopper)

**Comment by Leomelati** [comment]
@RAtwood90 Wowhead fixed the icons!
Can you check if it's working now?

**Comment by RAtwood90** [comment]
> @RAtwood90 Wowhead fixed the icons! Can you check if it's working now?

Yeah! It's fixed! Thanks!
