### ISSUE TITLE
Missing new mounts from patch 10.2

### ISSUE THREAD

**Issue by larryeltee** [kevinclement/SimpleArmory#558]
Hello, we are currently missing the [new mounts from the patch 10.2](https://www.wowhead.com/guide/mounts-patch-10-2):

**Comment by ttag12** [comment]
would be really nice if these updates come into the system faster than weeks after release of patches.

**Comment by seirl** [comment]
The data importer can handle PTR files just fine, I was using them a while ago to do updates.
