### ISSUE TITLE
All my achievements arent there

### ISSUE THREAD

**Issue by Alystale** [kevinclement/SimpleArmory#565]
How can I get all my achievements right?

**Comment by kevinclement** [comment]
You should double check you don't have the option toggle in Gameplay->Social->Display Only Characters.  See screen shot below.  If this is checked, the armory will only return achievements for the current character and not across all characters.  Uncheck this and logout and it should be fixed.  

![Screenshot 2023-12-30 at 5 41 09 PM](https://github.com/kevinclement/SimpleArmory/assets/132959/210bef97-ec7f-4f81-956a-2d0b29b58ccf)
