### ISSUE TITLE
Few 10.2 things missing or incorrectly placed

### ISSUE THREAD

**Issue by SolestialDev** [kevinclement/SimpleArmory#567]
Noticed a couple things were missing still or located in the wrong place. (Might be more but these I have noticed so far, will comment if I find anything else)

**Winterveil feat of strengths for the new gifts (missing)**
- [Catch Me If You Can!](https://www.wowhead.com/achievement=19077/catch-me-if-you-can)
- [Junior Racing Champion](https://www.wowhead.com/achievement=19130/junior-racing-champion)

**New M+ titles** 
These are currently located under Titles --> Legacy, when they should be under Titles --> Dragonflight --> Mythic Plus
- [the Dreaming](https://www.wowhead.com/title=786/the-dreaming) 
- [the Dreaming Hero](https://www.wowhead.com/title=800/the-dreaming-hero)

**New Reputation titles:**
- [the Dream Defender](https://www.wowhead.com/title=801/dream-defender)

**New PVP titles:**
Battle Mender should be located under Titles --> PVP --> Solo Shuffle, is currently missing
- [Battle Mender](https://www.wowhead.com/title=798/battle-mender)

These are currently located under Titles --> Legacy --> End of season Arena, when they should be located under Titles --> PVP --> Solo Shuffle/Arena
- [Verdant Legend](https://www.wowhead.com/title=794/verdant-legend)
- [Verdant Gladiator](https://www.wowhead.com/title=795/verdant-gladiator)

**No longer obtainable titles that are still marked as obtainable**
- [the Smoldering Hero](https://www.wowhead.com/title=771/the-smoldering-hero)
- [Famed Slayer of Sarkareth](https://www.wowhead.com/title=773/famed-slayer-of-sarkareth)
- [Obsidian Legend](https://www.wowhead.com/title=767/obsidian-legend)
- [Obsidian Gladiator](https://www.wowhead.com/title=766/obsidian-gladiator)

**Amirdrassil raid glory achievements**
Not missing or incorrectly located but the order of the Amirdrassil glory achievements are just in random order would appreciate if that could be fixed as well.
- Current order: Larodar --> Council --> Smolderon --> Igira --> Volcoross --> Gnarlroot --> Fyrakk --> Tindral --> Nymue
- Correct order: Gnarlroot --> Igira --> Volcoross --> Council --> Larodar --> Nymue --> Smolderon --> Tindral --> Fyrakk

Wasn't sure whether to link Titles or Achievements so they all link to the titles right now, if you'd rather have the achievement links just let me know and I will update this to have those instead.

**Comment by SolestialDev** [comment]
Adding to this, the Feat of Strength for Fyr'alath seems to be missing as well:
[Fyr'alath the Dreamrender](https://www.wowhead.com/achievement=19450/fyralath-the-dreamrender)

**Comment by kevinclement** [comment]
Thanks for reporting all of this.  I just pushed changes to update to 10.2.5 that is coming out tomorrow, so DB should be up to date.  I then went through your list of stuff and made any fixes needed on top.  Please double check to make sure I did it all proper and let me know if I didnt.

[x] Catch Me If You Can!
[x] Junior Racing Champion
[x] the Dreaming
[x] the Dreaming Hero
[x] the Dream Defender
[x] Battle Mender
[x] Verdant Legend
[x] Verdant Gladiator
[x] the Smoldering Hero	
[x] Famed Slayer of Sarkareth
[x] Obsidian Legend
[x] Obsidian Gladiator
[x] Correct order: Gnarlroot --> Igira --> Volcoross --> Council --> Larodar --> Nymue --> Smolderon --> Tindral --> Fyrakk
[x] Fyr'alath the Dreamrender
[x] Fyrn
