### ISSUE TITLE
Missing Mounts @ Dragonflight

### ISSUE THREAD

**Issue by Fluke667** [kevinclement/SimpleArmory#575]
https://www.wowhead.com/item=208152/patties-cap

Pattie is Missing and much more Dragonflight Mounts missing @Dragonflight

**Comment by kryptonite** [comment]
Pattie is not a Dragonflight mount. Its listed under the "World Events" -> "Secrets of Azeroth
" category.
![Capture](https://github.com/kevinclement/SimpleArmory/assets/1089576/0a5e4b46-ab9a-4daa-8e04-cba9b06bfb24)

**Comment by SolestialDev** [comment]
As far as I'm aware every Dragonflight mount that was added & is available is listed correctly.

**Comment by kevinclement** [comment]
Closing issues, agree with others, DB is caught up.
