### ISSUE TITLE
Visual update messed up quite a few things 

### ISSUE THREAD

**Issue by SolestialDev** [kevinclement/SimpleArmory#577]
With the latest update both alliance and horde versions are showing up for single characters, (with the opposite side noted as missing)
![alliance-horde1](https://github.com/kevinclement/SimpleArmory/assets/150586735/a4c3bbd1-3625-47a0-9b39-6b4b686173f4)
![alliance-horde2](https://github.com/kevinclement/SimpleArmory/assets/150586735/15654a6b-8cd9-48e5-9e78-9b3d03074ddc)
![alliance-horde3](https://github.com/kevinclement/SimpleArmory/assets/150586735/248e1e1b-7cb5-4446-b342-149dd225090f)

It also caused all unobtainable achievements to be listed again, it's especially problematic in the feat of strengths. If this is intended, please add a toggle between obtainable and unobtainable achievements, it looks a mess and makes it really hard to get a clear view of what someone still can get. (It does this correctly for mounts)
![unobtain-1](https://github.com/kevinclement/SimpleArmory/assets/150586735/1ec4099a-5554-4da5-92d8-de35b5104d73)
![feat1](https://github.com/kevinclement/SimpleArmory/assets/150586735/a232b67f-43b6-41c5-b427-dfc57927a522)

It also causes a lot of items/achievements to display the wrong link when hovering when swapping between pages, not correcting itself until the entire page is reloaded.
![wrong-link](https://github.com/kevinclement/SimpleArmory/assets/150586735/cbfa3728-3ab7-42c7-9014-39999e2d83d7)

I am quite positive about the greyed out display for achievements/mounts though, but hoping these issues can be fixed soon.

**Comment by MBabik01** [comment]
I still have this exact issue, is the fix not live yet?

**Comment by SolestialDev** [comment]
> I still have this exact issue, is the fix not live yet?

It is not & so far the fix only applies to the horde/alliance issue. We haven't received any update as to whether the unobtainable achievements issue was intended & if it is going to be addressed.
