### ISSUE TITLE
Mount Page updates

### ISSUE THREAD

**Issue by Dawndragon9** [kevinclement/SimpleArmory#584]
Hey, 
Unsure if it's been mentioned or notified, however since the gilneas mount was added in, it seems the mount collection page has ceased pulling through updates to reflect changes to the over-all mount collection tab. I'm not sure of what the actual issue is, just wanted to update you.

**Comment by SolestialDev** [comment]
I had this same issue a few days ago but it did fix itself after about 12 hours. I'm thinking it might have something to do on blizzard's side.

**Comment by Dawndragon9** [comment]
I have seen that happen before as well, but it's been close to 48 hours since an update has pulled through for me, so thought there may have been a deeper underlying issue

**Comment by yunfei-m** [comment]
Have the same issue. My mount profile has not updated for almost a week now.

**Comment by SolestialDev** [comment]
Could you perhaps provide any details of the character you're having problems with so I could test it & see if I can find a reason?

**Comment by kevinclement** [comment]
closing ticket for now as most of us aren't having trouble getting data. maybe just a hiccup?
