### ISSUE TITLE
Impus missing in Legion Fishing Masters in Reputation tab

### ISSUE THREAD

**Issue by pomelux** [kevinclement/SimpleArmory#586]
In the Legion Fishing Masters in the Reputation tab, there's one missing reputation (Impus). The faction id is 2102 https://www.wowhead.com/faction=2102/

**Comment by kevinclement** [comment]
Whoops, went to make the fix and noticed we actually do have it on the site.  There is a Legion Fishing Masters section under legion and Impus is there. 

![image](https://github.com/kevinclement/SimpleArmory/assets/132959/3aa820c0-8b4e-4de7-bbd3-d82a4f1fd47d)
