### ISSUE TITLE
Discussing Promotion mounts section

### ISSUE THREAD

**Issue by SolestialDev** [kevinclement/SimpleArmory#590]
Would like to discuss a few changes I'd like to make to the promotion section of the mounts page, but wanted to make sure it reflects what most people want before I work on it:

Few points I'd like to discuss:
- Should store mounts that have been removed from the store have the 'Not Obtainable' flag?
- Should mounts that are exclusive to the 12 month subscription be in 'Annual Pass' rather than 'Blizzard Store'?
- If mounts are "re-sourced", e.g. they are originally store mounts but are then moved to the trading post, should their category be changed?

**Comment by kevinclement** [comment]
agreed.  I think your recent change applied all of this logic.

**Comment by SolestialDev** [comment]
It did not, mostly focused on correcting things being obtainable/unobtainable (but chose to exclude store mounts for the time being), but I will get started on those changes tomorrow.

**Comment by SolestialDev** [comment]
Had some spare time to make the changes, couple things I'd like to discuss beforehand so I can adjust accordingly:
- Would you like to keep the Promotion --> Collector's Edition section? All of these mounts are now store mounts and going by the same logic applied to the trading post it would make sense to move them.

- I was considering making a special category for the mounts that have been last available through Twitch Prime/Drops, thoughts?

- I do see an eventual problem where this re-sourcing may lead to the Trading Post category being too full, might need to think of solutions for this, I was thinking maybe differentiating Trading Post Originals from Trading Post Re-Releases.

- I was considering moving the 'X-51 Nether-Rocket X-TREME' and 'Wooly White Rhino' from 'Trading Card Game' to the BMAH section. Since that's how they can be obtained nowadays and it would be consistent with how the 'Riding Turtle' mount was handled. Do you agree?

Would love to hear what you (and perhaps others as well if they end up reading this) think

**Comment by kevinclement** [comment]
Feels like change #591 fixed this.

**Comment by SolestialDev** [comment]
Would still like to get answers to these, which are not implemented yet:

- Would you like to keep the Promotion --> Collector's Edition section as is? Most of these mounts are now store mounts and going by the same logic applied to the trading post it would make sense to move them.

- I was considering making a special category for the mounts that have been last available through Twitch Prime/Drops, thoughts?

- I do see an eventual problem where this re-sourcing may lead to the Trading Post category being too full, might need to think of solutions for this, I was thinking maybe differentiating Trading Post Originals from Trading Post Re-Releases.

- I was considering moving the 'X-51 Nether-Rocket X-TREME' and 'Wooly White Rhino' from 'Trading Card Game' to the 'BMAH' section. Since that's how they can be obtained nowadays and it would be consistent with how the 'Riding Turtle' mount was handled. Do you agree?
