### ISSUE TITLE
Dragonwrath, Tarecgosa`s Rest

### ISSUE THREAD

**Issue by OnlyMM** [kevinclement/SimpleArmory#592]
After finish the legendry quest line and got an achievements the mount not showing on ( simple armory ) its been 2 weeks or more .

**Comment by SolestialDev** [comment]
Just to clarify, you have done the questline to unlock the actual mount as well right? Not just the legendary item questline

**Comment by OnlyMM** [comment]
Well, I think i only did questline fot the staff im not sure tho Can you send me link how to unlock actual mount 

thanks.

**Comment by kevinclement** [comment]
looks like you guys got this sorted out.
