### ISSUE TITLE
Obsidian Worldbreaker only through the BMAH

### ISSUE THREAD

**Issue by ex3qtr** [kevinclement/SimpleArmory#595]
Obsidian Worldbreaker is no longer available through the Anniversary Event. Only through the BMAH. Should it therefore perhaps slip into the BMAH category instead?

**Comment by SolestialDev** [comment]
I briefly considered moving both Core Hound & Obsidian Worldbreaker to BMAH in the recent updates to the section but decided against it for the same reason Collector's Edition mounts aren't under Store despite them now being store mounts; I think for some mounts it makes sense to keep them in their original section, whilst for others it doesn't.

Would be curious what others think as well though.

**Comment by F0ri0n** [comment]
Personally, I would prefer if mounts/pets would keep their original sources because now it's kind of inconsistent.

Tyrael's Charger for example had 4 sources (Annual Pass, Store, D4 Event, Trading Post).
Some of the RAF pets and TCG mounts were available through Twitch Prime

I think it also creates additional work to always update to the most recent source of an item.

**Comment by seirl** [comment]
From a mount collector's perspective, I think it's better to have the website be a current snapshot of all the mounts you can still obtain, and how you can obtain them. So I would go with updating the mount sources to be the most recent place you can get it from.

The question is what do you do when they become unavailable again. For example, with the Twitch Prime mounts, I would probably put them back again in the TCG mount category after the end of the twitch prime event.

**Comment by SolestialDev** [comment]
> The question is what do you do when they become unavailable again. For example, with the Twitch Prime mounts, I would probably put them back again in the TCG mount category after the end of the twitch prime event.

In my opinion they should reflect the latest source, so unless they become available again through another way they should stay there. I did bring up adding a Twitch Prime/Drops category before though so good to see there is interest for it at the very least.

**Comment by F0ri0n** [comment]
@SolestialDev 
Thanks for the clarification. I do see your points. For me, it was just always convenient to easily identify mounts exclusively obtainable through the Trading Post and having that satisfaction of a completed subcategory from the past. But I understand that for the majority of users, it might be more practical to always have the most recent source listed. I do still see an issue with fringe cases like the anniversary mounts or some of the Collector's Edition mounts (also purchasable on the store) however, which make it harder to ensure consistency.

**Comment by SolestialDev** [comment]
@F0ri0n 
>For me, it was just always convenient to easily identify mounts exclusively obtainable through the Trading Post and having that satisfaction of a completed subcategory from the past.
>
Would you think a split between Trading Post Originals & Trading Post Re-releases (so mounts that were originally available through other means but then put on the trading post) is something that would improve this? When I moved all of those mounts to Trading Post, I did see the potential problem of eventually having a section that's way too full and proposed splitting them, so perhaps that could be the solution if others agree its an improvement.

> I do still see an issue with fringe cases like the anniversary mounts or some of the Collector's Edition mounts (also purchasable on the store) however, which make it harder to ensure consistency.
>
I think an argument could be made for the collector's edition mounts as they have feat of strengths attached, specifically mentioning their original source, even when buying them from the store thus making them slightly different at the very least. But perhaps you are right on the Anniversary mounts belonging with BMAH now.

**Comment by F0ri0n** [comment]
@SolestialDev 
I think having the trading post category split between Originals and Re-releases is a great idea. This would at least mitigate the section becoming too crowded over time.

**Comment by SolestialDev** [comment]
Closing this now, since I'm pretty sure all of this has been implemented by now.
