### ISSUE TITLE
Achievements not visible

### ISSUE THREAD

**Issue by Mezir69** [kevinclement/SimpleArmory#598]
Hello,
i see in my achievements page many achivements that i've earned but still grayed out as they were not completed.

Luca

**Comment by Mezir69** [comment]
Yo u can check for example the achievement for Draenor exploration

**Comment by SolestialDev** [comment]
Could you provide us with a character name + realm so we can check what might be happening here?

**Comment by Mezir69** [comment]
> Could you provide us with a character name + realm so we can check what might be happening here?

Pg Mezir Server Pozzo D’Eternita’

**Comment by SolestialDev** [comment]
I looked at the character & can indeed see that you do have the criteria for these achievements, however I also looked at your wow armory and noticed these achievements are not granted to you on there either.

Could you verify that you have the achievements ingame on that character? If so, it's likely on blizzard's end and there's not much that can be done about it.

**Comment by Mezir69** [comment]
Ok, i’ll check on blizzard side and let you know 

many thanks
BR
Luca

**Comment by SolestialDev** [comment]
Hi, we haven't heard back from you on this in a while so I'm assuming this is sorted and can be closed now. Please let us know if you encounter any more issues! 😄
