### ISSUE TITLE
Categories for mounts

### ISSUE THREAD

**Issue by higginz** [kevinclement/SimpleArmory#616]
First of all, thank you for this page and the regular updates based on various user feedbacks. My comment primarily concerns the categorization of some mounts.

- All Blizzcon mounts are not really obtainable anymore. Apart from that, I am not aware of any way to get **Wandering Ancient** via ebay etc. So at least this mount should be **Unobtainable**.

- **Obsidian Worldbreaker** is only available via the **Black AH**.

- There are various items (including toys) that require PVP content in order to obtain them:

  - **Conqueror's Scythemaw**
  - **Pale Thorngrazer**
  - **Breezestrider Stallion**
  - **N'lyeth, Sliver of N'Zoth**
  - **Kowalski's Music Box**
  - **LeBlanc's Recorder**

I would like to see these items moved to the **PVP category**, like **Halaa** and **Talon's Vengeance**. I find it helpful so that a pure PVE player can really work through a specific list completely. Maybe I'm not alone with this opinion.

The situation is different with **Horde War Standard**, for example, as the required **Nazjatar Battle Commendation** can also be obtained through PVE content alone.

**Comment by SolestialDev** [comment]
> * All Blizzcon mounts are not really obtainable anymore. Apart from that, I am not aware of any way to get **Wandering Ancient** via ebay etc. So at least this mount should be **Unobtainable**.

They can still be bought through gold through re-sellers, which is why they are marked as obtainable. Wandering Ancient comes with buying any version of the base game.
![image](https://github.com/kevinclement/SimpleArmory/assets/150586735/a0591767-399a-4e59-9fe5-678993053575)

> * **Obsidian Worldbreaker** is only available via the **Black AH**.
This is also the case for the Core Hound mount, this was brought up before and the preferred opinion was to leave it in its original place, same with any of the Collector's Edition mounts that can be bought through the store nowadays.

> There are various items (including toys) that require PVP content in order to obtain them:
> 
> * **Conqueror's Scythemaw**
> * **Pale Thorngrazer**
> * **Breezestrider Stallion**
> * **N'lyeth, Sliver of N'Zoth**
> * **Kowalski's Music Box**
> * **LeBlanc's Recorder**

Will see how to resolve this, might just be in the form of adding a PVP sub-section to the expansion it is from because the PVP section is really intended for general pvp content (like honor level, arena rewards etc.), which none of these (including ivory hawkstrider and ashhide mushan beast) are. But is noted and will be handled in some way in the next update (probably in a few days)

**Comment by higginz** [comment]
> > * All Blizzcon mounts are not really obtainable anymore. Apart from that, I am not aware of any way to get **Wandering Ancient** via ebay etc. So at least this mount should be **Unobtainable**.
> 
> They can still be bought through gold through re-sellers, which is why they are marked as obtainable. Wandering Ancient comes with buying any version of the base game. (Comment on the Wandering Ancient page on wowhead)

I understand the point about resellers and it kind of makes sense to me. But with **Wandering Ancient** it's just not true. I have the current retail version of the game and not the mount. So there is obviously no way to get this mount at the moment.

> > * **Obsidian Worldbreaker** is only available via the **Black AH**.
> 
> This is also the case for the Core Hound mount, this was brought up before and the preferred opinion was to leave it in its original place, same with any of the Collector's Edition mounts that can be bought through the store nowadays.

I've just looked at the previous post on this again and I basically understand this argument. It's certainly not always easy to find a categorization, especially when some sources change over time. However, some **TCG mounts** have already been moved to the **Black AH** category. Therefore, it has already been taken into account that there is another way to obtain them, which is also much easier. 
With the **Anniversary Items**, however, there is no longer even a second option for obtaining them. In this respect, there are only two logical options for me: All those items should be marked as **unavailable** or moved to the **Black AH** category. Both options would be clearer, although to be fair, only the second option is one hundred percent correct. 
 
> > There are various items (including toys) that require PVP content in order to obtain them:
> > 
> > * **Conqueror's Scythemaw**
> > * **Pale Thorngrazer**
> > * **Breezestrider Stallion**
> > * **N'lyeth, Sliver of N'Zoth**
> > * **Kowalski's Music Box**
> > * **LeBlanc's Recorder**
> 
> Will see how to resolve this, might just be in the form of adding a PVP sub-section to the expansion it is from because the PVP section is really intended for general pvp content (like honor level, arena rewards etc.), which none of these (including ivory hawkstrider and ashhide mushan beast) are. But is noted and will be handled in some way in the next update (probably in a few days)

I am pleased that this topic is already being addressed. Personally, I would actually find it better if all PVP-related items were given their own category. One subcategory per addon would probably feel a bit lost, also because there aren't that many of them. PVP in itself is special enough and would generate its own list that PVP players could dedicate themselves to. With **Reins of the Black War Bear** there is even already another achievement mount on that list.

**Comment by kevinclement** [comment]
I don't think I ever got to commented on the other issue when some of this similar stuff came up.  Or maybe I commented I like them in collectors edition, but I ultimately I think I side on the logical argument, that the site is used in present time to help find missing stuff, so stuff that is attainable should be in the categories that best represent how to attain it today.

**Comment by higginz** [comment]
Thank you for implementing my suggestions! I also like the new category **Limited Time** at the top, which gives an additional overview. 

Furthermore I noticed a few more things:

- I can't find the toy **N'lyeth, Sliver of N'Zoth** at all now, not even under the **PVP** category. Maybe it was accidentally marked as **Unobtainable**?

- The pet **Lil' Nefarian**, like the mount **Obsidian Worldbreaker**, can only be obtained via the **Black AH**. On the other hand, the **Anniversary** category could also be moved to **World Events** for pets. I think this change to the mounts is already quite appropriate.

- The **Hyper-Compressed Ocean** toy is the reward for a pure Fishing Achievement **Secret Fish and Where to Find Them**. Equivalent to the Achievement **The Coin Master** and the toy **Titanium Seal of Dalaran**, it would be better placed in the **Professions** category. 

**Last but not least, another topic that I think has been discussed here before: Why aren't the Companions marked in the same way as the Battle Pets in terms of their rarity? I personally find the solution with the colored bar under the icon very appealing and would therefore like to see it for all pets.**

Otherwise, many thanks again for the exchange here and the quick implementation of the many suggestions!

**Comment by higginz** [comment]
Thank you for implementing my suggestions! I also like the new category **Limited Time** at the top, which gives an additional overview. 

Furthermore I noticed a few more things:

- I can't find the toy **N'lyeth, Sliver of N'Zoth** at all now, not even under the **PVP** category. Maybe it was accidentally marked as **Unobtainable**?

- The pet **Lil' Nefarian**, like the mount **Obsidian Worldbreaker**, can only be obtained via the **Black AH**. On the other hand, the **Anniversary** category could also be moved to **World Events** for pets. I think this change to the mounts is already quite appropriate.

- The **Hyper-Compressed Ocean** toy is the reward for a pure Fishing Achievement **Secret Fish and Where to Find Them**. Equivalent to the Achievement **The Coin Master** and the toy **Titanium Seal of Dalaran**, it would be better placed in the **Professions** category. 

**Last but not least, another topic that I think has been discussed here before: Why aren't the Companions marked in the same way as the Battle Pets in terms of their rarity? I personally find the solution with the colored bar under the icon very appealing and would therefore like to see it for all pets.**

Otherwise, many thanks again for the exchange here and the quick implementation of the many suggestions!

**Comment by SolestialDev** [comment]
> I can't find the toy N'lyeth, Sliver of N'Zoth at all now, not even under the PVP category. Maybe it was accidentally marked as Unobtainable?

It is currently unobtainable, it was supposed to go away with the Shadowlands launch but ended up sticking around slightly longer. It has not been obtainable since at least 9.0.5

> The pet Lil' Nefarian, like the mount Obsidian Worldbreaker, can only be obtained via the Black AH. On the other hand, the Anniversary category could also be moved to World Events for pets. I think this change to the mounts is already quite appropriate.

Will fix next update

> The Hyper-Compressed Ocean toy is the reward for a pure Fishing Achievement Secret Fish and Where to Find Them. Equivalent to the Achievement The Coin Master and the toy Titanium Seal of Dalaran, it would be better placed in the Professions category.

Will also fix next update.

> Last but not least, another topic that I think has been discussed here before: Why aren't the Companions marked in the same way as the Battle Pets in terms of their rarity? I personally find the solution with the colored bar under the icon very appealing and would therefore like to see it for all pets.

I'm not 100% sure here but I believe this is because those listed under 'Companions' only come in a single rarity per pet, so there's no need to display it, since there's no way to "improve" it beyond just collecting it. I personally don't think it really needs changing, but would love to hear what others think.

**Comment by higginz** [comment]
> It is currently unobtainable, it was supposed to go away with the Shadowlands launch but ended up sticking around slightly longer. It has not been obtainable since at least 9.0.5

Good to know, I was actually unaware of this.

> I'm not 100% sure here but I believe this is because those listed under 'Companions' only come in a single rarity per pet, so there's no need to display it, since there's no way to "improve" it beyond just collecting it. I personally don't think it really needs changing, but would love to hear what others think.

It is true that all Companions have a differently defined rarity. Some are already classified as rare and can no longer be upgraded in terms of rarity. But there are also Companions that are initially common or uncommon and can be upgraded. 

What would also be interesting is a representation of the level of all pets as a small white number in the corner or something similar. In this context, you could also give the few pets that cannot fight and therefore cannot be upgraded in any way their own category.

**Comment by higginz** [comment]
Any Update on this? I would very much like to see a corresponding adjustment, especially on the subject of **representation of the rarity of pets**.

**Comment by SolestialDev** [comment]
Implemented in #630
