### ISSUE TITLE
Legion Class Hall Mounts

### ISSUE THREAD

**Issue by mririgoyen** [kevinclement/SimpleArmory#621]
Might I inquire to the reasoning why all Legion class mounts show up on every character?

If I'm a Mage, I can only earn the Mage mounts. I can only use the Mage mounts. I shouldn't see every other class's mount on my Mage, right? The inclusion of every class mount skews the total number of mounts known/available for a given character.

**Comment by seirl** [comment]
The logic is to have all the mounts that count towards the achievements. Some mounts are "paired" with their opposite faction counterpart, and earning one automatically earns the other, and they only count as one for the achievement, so these are not displayed.

Some class-only mounts do count for the achievement but only for the characters of this class, e.g. the paladin and DH mounts.

However, legion class hall mounts do count for the achievement *regardless of which character you're in*. Unlike class-only mounts and paired faction mounts, they're cumulative, so you make meaningful account-wide progress by collecting them all.

Hope that clarifies it!

**Comment by mririgoyen** [comment]
I'm not sure this clarifies much for me, to be honest. How is it determined that other class's mounts count towards another? Why are, for example, the four rogue mounts missing when I look at my hunter, but all the others are there?

Additionally, since we're on the subject, and since it sounds like you might have some insight into it... Why are all the mount numbers so inconsistent amoung all the different trackers? Enhanced Mount Journal gives me one number, SimpleArmory gives me another, WoWthing yet another... It seems like there is a lot of guesswork going on here, so I'm curious to learn more.
