### ISSUE TITLE
Blessed Defender of Nordrassil bug in Titles (Delegation)

### ISSUE THREAD

**Issue by Isareth** [kevinclement/SimpleArmory#624]
The Delegation quest in Titles doesn't show complete on my character that I've completed the Delegation/Legendary staff quest on.
Also, this title is technically temporary and not a permanent title which might be also causing it to show appear?

**Comment by SolestialDev** [comment]
Will remove in next update, is indeed temporary so shouldn't be listed as something collectable.

**Comment by SolestialDev** [comment]
Fixed in #627
