### ISSUE TITLE
Missing a couple TWW mounts

### ISSUE THREAD

**Issue by d-ellis** [kevinclement/SimpleArmory#631]
Been playing through and noticed a couple mounts that aren't listed on Simple Armory:
- [Siesbarg](https://www.wowhead.com/item=224150/siesbarg)
- [Kah, Legend of the Deep](https://www.wowhead.com/item=223286/kah-legend-of-the-deep)

Not sure if this is an issue in this repo or with some external provider. I might investigate and look at making a PR myself, but I'd have to learn the setup first which could take me a while

**Comment by SolestialDev** [comment]
Both of these are listed, Siesbarg is listed under 'Rare Spawn' (as it's quest starter is a drop from a rare spawn), and Kah, Legend of the Deep is listed under Professions > Fishing.

**Comment by d-ellis** [comment]
Ah yeah so they are. My mistake. I was looking for Kah under Achievements as it's an achievement reward, and Siesbarg under quest due to its quest chain :sweat_smile:
Closing this issue then as it's just me missing them
