### ISSUE TITLE
War Within Profession -toys- marked 'unobtainable'.

### ISSUE THREAD

**Issue by mmofanatic90210** [kevinclement/SimpleArmory#635]
The Jewelcrafting and Engineering toys are only visible if you have 'show unobtainable' On. 
The toys are very much obtainable. Leftover flagging from War Within pre-release setup?

**Comment by SolestialDev** [comment]
Ah my bad, completely missed these. Will be fixed asap

**Comment by SolestialDev** [comment]
Fixed in #638
