### ISSUE TITLE
Some pets still in the wrong place 

### ISSUE THREAD

**Issue by F0ri0n** [kevinclement/SimpleArmory#645]
Currently, 3 out of the 4 pets listed under TWW -> World are actually capturable in various zones, so they should be relocated to the Battle Pets category:

- Mossy Snail (Isle of Dorn)
- Azure Flickerfly (Multiple Zones)
- Vibrant Glowfly (Multiple Zones)

The fourth pet, Shadowbog Hopper, is obtained by pulling vines in Hallowfall (with a low drop chance), so it may be more appropriate to move it to TWW -> Treasure.

On a side note, I noticed that the mount categories all use the full expansion name while the WoD category is only called 'Draenor'. For consistency, I would rename it 'Warlords of Draenor'. But this is just a minor thing.

Thanks for maintaining this site!

**Comment by SolestialDev** [comment]
Fix for this is now live
