### ISSUE TITLE
Missing Achievement Mount

### ISSUE THREAD

**Issue by rbflinn0** [kevinclement/SimpleArmory#647]
In The War Within you can get the Derby Dash achievement and the reward is Kah, Legend of the Deep. I didn't see any mentions about this and just wanted to bring it to your attention just in case you didn't know. I've linked the WoWHead page about the achievement below. Thanks for all you do and for making/maintaining this website :)

https://www.wowhead.com/achievement=40539/the-derby-dash#comments

**Comment by SolestialDev** [comment]
Hi, this mount is listed under Professions > Fishing, as it is a Fishing achievement.
