### ISSUE TITLE
Warband Characters not matching achievements or collectables

### ISSUE THREAD

**Issue by Raginmunnd** [kevinclement/SimpleArmory#655]
![Fenriom](https://github.com/user-attachments/assets/b1d3a84d-3d14-4e16-a518-1720a38a0e9c)
![Panathia](https://github.com/user-attachments/assets/4c6e2259-18c5-4057-a8c0-0cf82bb6a5b7)

Hi,

I wanted to raise an issue where my night elf druid who has been my main has got alot of achievements in particular got all classic raid achievements. But my worgen or any other of my alts has it greyed out. This is for achievements but also for collectables. I've sent screenshot to show my issue. This used to work and be fine but since then it doesn't work anymore

**Comment by SolestialDev** [comment]
Hi,

I just checked with all of my alts and the achievements match as intended so not sure what's going on here

So I just want to confirm:
Have you logged in on these alts since you got the achievements? (the API data on blizzard's end only updates on logout on a per character basis)

If so, please give me some character+realm names and I'll take a closer look.

**Comment by Raginmunnd** [comment]
I have checked logged in since. The classic raids and some TBC heroic dungeons would have been done over 2 weeks ago.

Panathia which is my main
Fenriom
Beithaka
Hairicín
Bhéara
Carnonos
Duinn

These are just a mixture of both horde and alliance and are all in the same realm EU stormscale.

What's unusual is that I was checking alts and some of them actually do have them filled in while others like the ones above apart from Panathia don't.

**Comment by Raginmunnd** [comment]
ah ok, that may be it. I'll give that a shot cause i do tend to exit now and would only log out if i was changing characters

**Comment by SolestialDev** [comment]
Since we haven't heard back in a while, assuming this is all sorted. So, closing this one now. 
Please let us know if you encounter any more issues 😄
