### ISSUE TITLE
Feats of Strength and Legacy pages are empty

### ISSUE THREAD

**Issue by robinsoj** [kevinclement/SimpleArmory#668]
# Problem:
The Feats of Strength and Legacy pages no longer display achievements earned from those categories.  Those pages were populated in the past.

# Steps to replicate:

1. Select **EU-Argent Dawn** as the realm
2. Enter **Studenalb** as the character
3. Select **Legacy** or **Feats of Strength** from the **Achievement** drop-down menu

# Character Armory Profile:
https://worldofwarcraft.blizzard.com/en-gb/character/eu/argent-dawn/studenalb/achievements

# Expected Result:

Display those pages with the relevant achievements.

**Comment by SolestialDev** [comment]
Hi, do you by any chance have the setting 'Show Only Unobtained' enabed? In the case of Feat of Strengths this is only supported if you also have the 'Show Obtainable Feat of Strengths' setting enabled - otherwise it will not list anything.

**Comment by robinsoj** [comment]
I had not changed any of the settings.  I messed around with them and turned the pages back on with the following setting configurations:

Hide Obtainable Feat of Strengths
Show Only Unobtained

**Comment by SolestialDev** [comment]
Oh that's strange. Hopefully it was just a visual error and it won't happen again. 

Please do let us know if it happens again so it can be looked into further :)
