### ISSUE TITLE
Dark mode setting

### ISSUE THREAD

**Issue by kevinclement** [kevinclement/SimpleArmory#87]
User Request:

Have a dark version theme for site.

**Comment by ThePrimoris** [comment]
This was posted back in 2016, has there been any leeway on this? Should be a simple button and some color swapping in css for a dark theme.

**Comment by seirl** [comment]
I'm not aware of anyone working on that. I'd be glad to review a contribution though!

**Comment by ThePrimoris** [comment]
> I'm not aware of anyone working on that. I'd be glad to review a contribution though!

https://i.imgur.com/dPc1pIX.png https://i.imgur.com/RECMVTk.jpg

Super quick mockup I made for a dark mode.

**Comment by seirl** [comment]
That looks reasonable, were you able to integrate that in the code? Could you make a pull request?

**Comment by ThePrimoris** [comment]
> That looks reasonable, were you able to integrate that in the code? Could you make a pull request?

I would but I couldn't figure out how to set up the copy on my desktop, i also saw that bower wasn't installing in one of the other issues

**Comment by seirl** [comment]
Bower is working fine, it's just deprecated.

**Comment by DHainzl** [comment]
I think this issue can be closed now that #192 is merged?

**Comment by seirl** [comment]
Yes, thank you!
